import { MODULE_REGISTRY, type UserPermissions } from "./module-registry";

export const ROLE_DEFAULTS: Record<"admin" | "teacher" | "parent", UserPermissions> = {
  admin: {
    dashboard:               { view: true },
    admission_new:           { view: true, create: true },
    admission_queue:         { view: true, approve: true, delete: false },
    madrassa_students:       { view: true, create: true, edit: true, delete: false, export: true, print: true },
    madrassa_attendance:     { view: true, create: true, edit: true, export: true },
    madrassa_fees:           { view: true, create: true, edit: true, delete: false, export: true, print: true },
    madrassa_categories:     { view: true, create: true, edit: true, delete: false },
    madrassa_exams_internal: { view: true, create: true, edit: true, delete: false, mark_entry: true, print: true, export: true },
    madrassa_exams_board:    { view: true, create: true, edit: true, export: true },
    madrassa_timetable:      { view: true, create: true, edit: true, delete: true, print: true },
    madrassa_hifz:           { view: true, create: true, edit: true },
    school_students:         { view: true, create: true, edit: true, delete: false, export: true, print: true },
    school_attendance:       { view: true, create: true, edit: true, export: true },
    school_fees:             { view: true, create: true, edit: true, delete: false, export: true, print: true },
    school_classes:          { view: true, create: true, edit: true, delete: false },
    school_exams_internal:   { view: true, create: true, edit: true, delete: false, mark_entry: true, print: true, export: true },
    school_exams_board:      { view: true, create: true, edit: true, export: true },
    school_timetable:        { view: true, create: true, edit: true, delete: true, print: true },
    teachers:                { view: true, create: true, edit: true, delete: false, print: true, export: true },
    id_cards:                { view: true, print: true },
    reports_attendance:      { view: true, export: true, print: true },
    reports_category:        { view: true, export: true, print: true },
    reports_results:         { view: true, export: true, print: true },
    reports_monthly:         { view: true, export: true, print: true },
    reports_annual:          { view: true, export: true, print: true },
    inventory:               { view: true, create: true, edit: true, delete: false, export: true },
    finance:                 { view: true, create: true, edit: true, delete: false, export: true, print: true },
    users:                   { view: false },
    settings_academic_year:  { view: true, manage: false },
    settings_holidays:       { view: true, create: true, edit: true, delete: true },
    settings_website:        { view: true, edit: true, manage: false },
    settings_audit:          { view: false },
  },
  teacher: {
    dashboard:               { view: true },
    madrassa_students:       { view: true },
    madrassa_attendance:     { view: true, create: true, edit: true },
    madrassa_categories:     { view: true },
    madrassa_exams_internal: { view: true, mark_entry: true },
    madrassa_exams_board:    { view: true },
    madrassa_timetable:      { view: true, print: true },
    madrassa_hifz:           { view: true, edit: true },
    school_students:         { view: true },
    school_attendance:       { view: true, create: true, edit: true },
    school_classes:          { view: true },
    school_exams_internal:   { view: true, mark_entry: true },
    school_exams_board:      { view: true },
    school_timetable:        { view: true, print: true },
    teachers:                { view: true },
    reports_attendance:      { view: true },
    reports_results:         { view: true },
    settings_academic_year:  { view: true },
    settings_holidays:       { view: true },
  },
  parent: {},
};

export function getSuperAdminPermissions(): UserPermissions {
  return Object.fromEntries(
    MODULE_REGISTRY.map((mod) => [
      mod.key,
      Object.fromEntries(mod.availableActions.map((a) => [a, true])),
    ]),
  ) as UserPermissions;
}