/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsiteRouteImport } from './routes/website'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WebsiteIndexRouteImport } from './routes/website.index'
import { Route as WebsiteGalleryRouteImport } from './routes/website.gallery'
import { Route as WebsiteContactRouteImport } from './routes/website.contact'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedParentsRouteImport } from './routes/_authenticated/parents'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedIdCardsRouteImport } from './routes/_authenticated/id-cards'
import { Route as AuthenticatedHolidaysRouteImport } from './routes/_authenticated/holidays'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedTeachersIndexRouteImport } from './routes/_authenticated/teachers.index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports.index'
import { Route as AuthenticatedFinanceIndexRouteImport } from './routes/_authenticated/finance.index'
import { Route as AuthenticatedAdmissionIndexRouteImport } from './routes/_authenticated/admission/index'
import { Route as AuthenticatedTeachersSalaryRouteImport } from './routes/_authenticated/teachers_.salary'
import { Route as AuthenticatedTeachersIdRouteImport } from './routes/_authenticated/teachers.$id'
import { Route as AuthenticatedStudentsIdRouteImport } from './routes/_authenticated/students.$id'
import { Route as AuthenticatedSettingsWebsiteRouteImport } from './routes/_authenticated/settings/website'
import { Route as AuthenticatedSettingsTemplatesRouteImport } from './routes/_authenticated/settings/templates'
import { Route as AuthenticatedSettingsConcessionsRouteImport } from './routes/_authenticated/settings/concessions'
import { Route as AuthenticatedSettingsBackupRouteImport } from './routes/_authenticated/settings/backup'
import { Route as AuthenticatedSettingsAcademicYearRouteImport } from './routes/_authenticated/settings/academic-year'
import { Route as AuthenticatedSchoolTimetableRouteImport } from './routes/_authenticated/school/timetable'
import { Route as AuthenticatedSchoolSubjectsRouteImport } from './routes/_authenticated/school/subjects'
import { Route as AuthenticatedSchoolStudentsRouteImport } from './routes/_authenticated/school/students'
import { Route as AuthenticatedSchoolFeesRouteImport } from './routes/_authenticated/school/fees'
import { Route as AuthenticatedSchoolClassesRouteImport } from './routes/_authenticated/school/classes'
import { Route as AuthenticatedSchoolAttendanceRouteImport } from './routes/_authenticated/school/attendance'
import { Route as AuthenticatedReportsMonthlyRouteImport } from './routes/_authenticated/reports.monthly'
import { Route as AuthenticatedReportsCategoryRouteImport } from './routes/_authenticated/reports.category'
import { Route as AuthenticatedReportsAttendanceRouteImport } from './routes/_authenticated/reports.attendance'
import { Route as AuthenticatedReportsAnnualRouteImport } from './routes/_authenticated/reports.annual'
import { Route as AuthenticatedMadrassaTimetableRouteImport } from './routes/_authenticated/madrassa/timetable'
import { Route as AuthenticatedMadrassaSubjectsRouteImport } from './routes/_authenticated/madrassa/subjects'
import { Route as AuthenticatedMadrassaStudentsRouteImport } from './routes/_authenticated/madrassa/students'
import { Route as AuthenticatedMadrassaHifzRouteImport } from './routes/_authenticated/madrassa/hifz'
import { Route as AuthenticatedMadrassaFeesRouteImport } from './routes/_authenticated/madrassa/fees'
import { Route as AuthenticatedMadrassaClassesRouteImport } from './routes/_authenticated/madrassa/classes'
import { Route as AuthenticatedMadrassaCategoriesRouteImport } from './routes/_authenticated/madrassa/categories'
import { Route as AuthenticatedMadrassaAttendanceRouteImport } from './routes/_authenticated/madrassa/attendance'
import { Route as AuthenticatedFinanceDonationsRouteImport } from './routes/_authenticated/finance_.donations'
import { Route as AuthenticatedAdmissionQueueRouteImport } from './routes/_authenticated/admission/queue'
import { Route as AuthenticatedAdmissionNewRouteImport } from './routes/_authenticated/admission/new'
import { Route as AuthenticatedAdmissionInterviewsRouteImport } from './routes/_authenticated/admission/interviews'
import { Route as AuthenticatedSchoolExamsIndexRouteImport } from './routes/_authenticated/school/exams.index'
import { Route as AuthenticatedMadrassaExamsIndexRouteImport } from './routes/_authenticated/madrassa/exams.index'
import { Route as AuthenticatedSchoolExamsBoardRouteImport } from './routes/_authenticated/school/exams.board'
import { Route as AuthenticatedMadrassaExamsBoardRouteImport } from './routes/_authenticated/madrassa/exams.board'
import { Route as AuthenticatedSchoolExamsIdIndexRouteImport } from './routes/_authenticated/school/exams.$id.index'
import { Route as AuthenticatedMadrassaExamsIdIndexRouteImport } from './routes/_authenticated/madrassa/exams.$id.index'
import { Route as AuthenticatedSchoolExamsIdSeatingRouteImport } from './routes/_authenticated/school/exams.$id.seating'
import { Route as AuthenticatedSchoolExamsIdResultsRouteImport } from './routes/_authenticated/school/exams.$id.results'
import { Route as AuthenticatedMadrassaExamsIdSeatingRouteImport } from './routes/_authenticated/madrassa/exams.$id.seating'
import { Route as AuthenticatedMadrassaExamsIdResultsRouteImport } from './routes/_authenticated/madrassa/exams.$id.results'
import { Route as AuthenticatedMadrassaExamsIdMarksRouteImport } from './routes/_authenticated/madrassa/exams.$id.marks'

const WebsiteRoute = WebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteIndexRoute = WebsiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebsiteRoute,
} as any)
const WebsiteGalleryRoute = WebsiteGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => WebsiteRoute,
} as any)
const WebsiteContactRoute = WebsiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => WebsiteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedParentsRoute = AuthenticatedParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIdCardsRoute = AuthenticatedIdCardsRouteImport.update({
  id: '/id-cards',
  path: '/id-cards',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHolidaysRoute = AuthenticatedHolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeachersIndexRoute =
  AuthenticatedTeachersIndexRouteImport.update({
    id: '/teachers/',
    path: '/teachers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceIndexRoute =
  AuthenticatedFinanceIndexRouteImport.update({
    id: '/finance/',
    path: '/finance/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdmissionIndexRoute =
  AuthenticatedAdmissionIndexRouteImport.update({
    id: '/admission/',
    path: '/admission/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeachersSalaryRoute =
  AuthenticatedTeachersSalaryRouteImport.update({
    id: '/teachers_/salary',
    path: '/teachers/salary',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeachersIdRoute = AuthenticatedTeachersIdRouteImport.update({
  id: '/teachers/$id',
  path: '/teachers/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentsIdRoute = AuthenticatedStudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsWebsiteRoute =
  AuthenticatedSettingsWebsiteRouteImport.update({
    id: '/settings/website',
    path: '/settings/website',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsTemplatesRoute =
  AuthenticatedSettingsTemplatesRouteImport.update({
    id: '/settings/templates',
    path: '/settings/templates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsConcessionsRoute =
  AuthenticatedSettingsConcessionsRouteImport.update({
    id: '/settings/concessions',
    path: '/settings/concessions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsBackupRoute =
  AuthenticatedSettingsBackupRouteImport.update({
    id: '/settings/backup',
    path: '/settings/backup',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAcademicYearRoute =
  AuthenticatedSettingsAcademicYearRouteImport.update({
    id: '/settings/academic-year',
    path: '/settings/academic-year',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSchoolTimetableRoute =
  AuthenticatedSchoolTimetableRouteImport.update({
    id: '/school/timetable',
    path: '/school/timetable',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSchoolSubjectsRoute =
  AuthenticatedSchoolSubjectsRouteImport.update({
    id: '/school/subjects',
    path: '/school/subjects',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSchoolStudentsRoute =
  AuthenticatedSchoolStudentsRouteImport.update({
    id: '/school/students',
    path: '/school/students',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSchoolFeesRoute = AuthenticatedSchoolFeesRouteImport.update({
  id: '/school/fees',
  path: '/school/fees',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSchoolClassesRoute =
  AuthenticatedSchoolClassesRouteImport.update({
    id: '/school/classes',
    path: '/school/classes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSchoolAttendanceRoute =
  AuthenticatedSchoolAttendanceRouteImport.update({
    id: '/school/attendance',
    path: '/school/attendance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsMonthlyRoute =
  AuthenticatedReportsMonthlyRouteImport.update({
    id: '/reports/monthly',
    path: '/reports/monthly',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsCategoryRoute =
  AuthenticatedReportsCategoryRouteImport.update({
    id: '/reports/category',
    path: '/reports/category',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsAttendanceRoute =
  AuthenticatedReportsAttendanceRouteImport.update({
    id: '/reports/attendance',
    path: '/reports/attendance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsAnnualRoute =
  AuthenticatedReportsAnnualRouteImport.update({
    id: '/reports/annual',
    path: '/reports/annual',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMadrassaTimetableRoute =
  AuthenticatedMadrassaTimetableRouteImport.update({
    id: '/madrassa/timetable',
    path: '/madrassa/timetable',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMadrassaSubjectsRoute =
  AuthenticatedMadrassaSubjectsRouteImport.update({
    id: '/madrassa/subjects',
    path: '/madrassa/subjects',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMadrassaStudentsRoute =
  AuthenticatedMadrassaStudentsRouteImport.update({
    id: '/madrassa/students',
    path: '/madrassa/students',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMadrassaHifzRoute =
  AuthenticatedMadrassaHifzRouteImport.update({
    id: '/madrassa/hifz',
    path: '/madrassa/hifz',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMadrassaFeesRoute =
  AuthenticatedMadrassaFeesRouteImport.update({
    id: '/madrassa/fees',
    path: '/madrassa/fees',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMadrassaClassesRoute =
  AuthenticatedMadrassaClassesRouteImport.update({
    id: '/madrassa/classes',
    path: '/madrassa/classes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMadrassaCategoriesRoute =
  AuthenticatedMadrassaCategoriesRouteImport.update({
    id: '/madrassa/categories',
    path: '/madrassa/categories',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMadrassaAttendanceRoute =
  AuthenticatedMadrassaAttendanceRouteImport.update({
    id: '/madrassa/attendance',
    path: '/madrassa/attendance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceDonationsRoute =
  AuthenticatedFinanceDonationsRouteImport.update({
    id: '/finance_/donations',
    path: '/finance/donations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdmissionQueueRoute =
  AuthenticatedAdmissionQueueRouteImport.update({
    id: '/admission/queue',
    path: '/admission/queue',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdmissionNewRoute =
  AuthenticatedAdmissionNewRouteImport.update({
    id: '/admission/new',
    path: '/admission/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdmissionInterviewsRoute =
  AuthenticatedAdmissionInterviewsRouteImport.update({
    id: '/admission/interviews',
    path: '/admission/interviews',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSchoolExamsIndexRoute =
  AuthenticatedSchoolExamsIndexRouteImport.update({
    id: '/school/exams/',
    path: '/school/exams/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMadrassaExamsIndexRoute =
  AuthenticatedMadrassaExamsIndexRouteImport.update({
    id: '/madrassa/exams/',
    path: '/madrassa/exams/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSchoolExamsBoardRoute =
  AuthenticatedSchoolExamsBoardRouteImport.update({
    id: '/school/exams/board',
    path: '/school/exams/board',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMadrassaExamsBoardRoute =
  AuthenticatedMadrassaExamsBoardRouteImport.update({
    id: '/madrassa/exams/board',
    path: '/madrassa/exams/board',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSchoolExamsIdIndexRoute =
  AuthenticatedSchoolExamsIdIndexRouteImport.update({
    id: '/school/exams/$id/',
    path: '/school/exams/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMadrassaExamsIdIndexRoute =
  AuthenticatedMadrassaExamsIdIndexRouteImport.update({
    id: '/madrassa/exams/$id/',
    path: '/madrassa/exams/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSchoolExamsIdSeatingRoute =
  AuthenticatedSchoolExamsIdSeatingRouteImport.update({
    id: '/school/exams/$id/seating',
    path: '/school/exams/$id/seating',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSchoolExamsIdResultsRoute =
  AuthenticatedSchoolExamsIdResultsRouteImport.update({
    id: '/school/exams/$id/results',
    path: '/school/exams/$id/results',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMadrassaExamsIdSeatingRoute =
  AuthenticatedMadrassaExamsIdSeatingRouteImport.update({
    id: '/madrassa/exams/$id/seating',
    path: '/madrassa/exams/$id/seating',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMadrassaExamsIdResultsRoute =
  AuthenticatedMadrassaExamsIdResultsRouteImport.update({
    id: '/madrassa/exams/$id/results',
    path: '/madrassa/exams/$id/results',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMadrassaExamsIdMarksRoute =
  AuthenticatedMadrassaExamsIdMarksRouteImport.update({
    id: '/madrassa/exams/$id/marks',
    path: '/madrassa/exams/$id/marks',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/website': typeof WebsiteRouteWithChildren
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/holidays': typeof AuthenticatedHolidaysRoute
  '/id-cards': typeof AuthenticatedIdCardsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/parents': typeof AuthenticatedParentsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/website/contact': typeof WebsiteContactRoute
  '/website/gallery': typeof WebsiteGalleryRoute
  '/website/': typeof WebsiteIndexRoute
  '/admission/interviews': typeof AuthenticatedAdmissionInterviewsRoute
  '/admission/new': typeof AuthenticatedAdmissionNewRoute
  '/admission/queue': typeof AuthenticatedAdmissionQueueRoute
  '/finance/donations': typeof AuthenticatedFinanceDonationsRoute
  '/madrassa/attendance': typeof AuthenticatedMadrassaAttendanceRoute
  '/madrassa/categories': typeof AuthenticatedMadrassaCategoriesRoute
  '/madrassa/classes': typeof AuthenticatedMadrassaClassesRoute
  '/madrassa/fees': typeof AuthenticatedMadrassaFeesRoute
  '/madrassa/hifz': typeof AuthenticatedMadrassaHifzRoute
  '/madrassa/students': typeof AuthenticatedMadrassaStudentsRoute
  '/madrassa/subjects': typeof AuthenticatedMadrassaSubjectsRoute
  '/madrassa/timetable': typeof AuthenticatedMadrassaTimetableRoute
  '/reports/annual': typeof AuthenticatedReportsAnnualRoute
  '/reports/attendance': typeof AuthenticatedReportsAttendanceRoute
  '/reports/category': typeof AuthenticatedReportsCategoryRoute
  '/reports/monthly': typeof AuthenticatedReportsMonthlyRoute
  '/school/attendance': typeof AuthenticatedSchoolAttendanceRoute
  '/school/classes': typeof AuthenticatedSchoolClassesRoute
  '/school/fees': typeof AuthenticatedSchoolFeesRoute
  '/school/students': typeof AuthenticatedSchoolStudentsRoute
  '/school/subjects': typeof AuthenticatedSchoolSubjectsRoute
  '/school/timetable': typeof AuthenticatedSchoolTimetableRoute
  '/settings/academic-year': typeof AuthenticatedSettingsAcademicYearRoute
  '/settings/backup': typeof AuthenticatedSettingsBackupRoute
  '/settings/concessions': typeof AuthenticatedSettingsConcessionsRoute
  '/settings/templates': typeof AuthenticatedSettingsTemplatesRoute
  '/settings/website': typeof AuthenticatedSettingsWebsiteRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/teachers/$id': typeof AuthenticatedTeachersIdRoute
  '/teachers/salary': typeof AuthenticatedTeachersSalaryRoute
  '/admission/': typeof AuthenticatedAdmissionIndexRoute
  '/finance/': typeof AuthenticatedFinanceIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/teachers/': typeof AuthenticatedTeachersIndexRoute
  '/madrassa/exams/board': typeof AuthenticatedMadrassaExamsBoardRoute
  '/school/exams/board': typeof AuthenticatedSchoolExamsBoardRoute
  '/madrassa/exams/': typeof AuthenticatedMadrassaExamsIndexRoute
  '/school/exams/': typeof AuthenticatedSchoolExamsIndexRoute
  '/madrassa/exams/$id/marks': typeof AuthenticatedMadrassaExamsIdMarksRoute
  '/madrassa/exams/$id/results': typeof AuthenticatedMadrassaExamsIdResultsRoute
  '/madrassa/exams/$id/seating': typeof AuthenticatedMadrassaExamsIdSeatingRoute
  '/school/exams/$id/results': typeof AuthenticatedSchoolExamsIdResultsRoute
  '/school/exams/$id/seating': typeof AuthenticatedSchoolExamsIdSeatingRoute
  '/madrassa/exams/$id/': typeof AuthenticatedMadrassaExamsIdIndexRoute
  '/school/exams/$id/': typeof AuthenticatedSchoolExamsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/holidays': typeof AuthenticatedHolidaysRoute
  '/id-cards': typeof AuthenticatedIdCardsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/parents': typeof AuthenticatedParentsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/website/contact': typeof WebsiteContactRoute
  '/website/gallery': typeof WebsiteGalleryRoute
  '/website': typeof WebsiteIndexRoute
  '/admission/interviews': typeof AuthenticatedAdmissionInterviewsRoute
  '/admission/new': typeof AuthenticatedAdmissionNewRoute
  '/admission/queue': typeof AuthenticatedAdmissionQueueRoute
  '/finance/donations': typeof AuthenticatedFinanceDonationsRoute
  '/madrassa/attendance': typeof AuthenticatedMadrassaAttendanceRoute
  '/madrassa/categories': typeof AuthenticatedMadrassaCategoriesRoute
  '/madrassa/classes': typeof AuthenticatedMadrassaClassesRoute
  '/madrassa/fees': typeof AuthenticatedMadrassaFeesRoute
  '/madrassa/hifz': typeof AuthenticatedMadrassaHifzRoute
  '/madrassa/students': typeof AuthenticatedMadrassaStudentsRoute
  '/madrassa/subjects': typeof AuthenticatedMadrassaSubjectsRoute
  '/madrassa/timetable': typeof AuthenticatedMadrassaTimetableRoute
  '/reports/annual': typeof AuthenticatedReportsAnnualRoute
  '/reports/attendance': typeof AuthenticatedReportsAttendanceRoute
  '/reports/category': typeof AuthenticatedReportsCategoryRoute
  '/reports/monthly': typeof AuthenticatedReportsMonthlyRoute
  '/school/attendance': typeof AuthenticatedSchoolAttendanceRoute
  '/school/classes': typeof AuthenticatedSchoolClassesRoute
  '/school/fees': typeof AuthenticatedSchoolFeesRoute
  '/school/students': typeof AuthenticatedSchoolStudentsRoute
  '/school/subjects': typeof AuthenticatedSchoolSubjectsRoute
  '/school/timetable': typeof AuthenticatedSchoolTimetableRoute
  '/settings/academic-year': typeof AuthenticatedSettingsAcademicYearRoute
  '/settings/backup': typeof AuthenticatedSettingsBackupRoute
  '/settings/concessions': typeof AuthenticatedSettingsConcessionsRoute
  '/settings/templates': typeof AuthenticatedSettingsTemplatesRoute
  '/settings/website': typeof AuthenticatedSettingsWebsiteRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/teachers/$id': typeof AuthenticatedTeachersIdRoute
  '/teachers/salary': typeof AuthenticatedTeachersSalaryRoute
  '/admission': typeof AuthenticatedAdmissionIndexRoute
  '/finance': typeof AuthenticatedFinanceIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/teachers': typeof AuthenticatedTeachersIndexRoute
  '/madrassa/exams/board': typeof AuthenticatedMadrassaExamsBoardRoute
  '/school/exams/board': typeof AuthenticatedSchoolExamsBoardRoute
  '/madrassa/exams': typeof AuthenticatedMadrassaExamsIndexRoute
  '/school/exams': typeof AuthenticatedSchoolExamsIndexRoute
  '/madrassa/exams/$id/marks': typeof AuthenticatedMadrassaExamsIdMarksRoute
  '/madrassa/exams/$id/results': typeof AuthenticatedMadrassaExamsIdResultsRoute
  '/madrassa/exams/$id/seating': typeof AuthenticatedMadrassaExamsIdSeatingRoute
  '/school/exams/$id/results': typeof AuthenticatedSchoolExamsIdResultsRoute
  '/school/exams/$id/seating': typeof AuthenticatedSchoolExamsIdSeatingRoute
  '/madrassa/exams/$id': typeof AuthenticatedMadrassaExamsIdIndexRoute
  '/school/exams/$id': typeof AuthenticatedSchoolExamsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/apply': typeof ApplyRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/website': typeof WebsiteRouteWithChildren
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/holidays': typeof AuthenticatedHolidaysRoute
  '/_authenticated/id-cards': typeof AuthenticatedIdCardsRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/parents': typeof AuthenticatedParentsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/website/contact': typeof WebsiteContactRoute
  '/website/gallery': typeof WebsiteGalleryRoute
  '/website/': typeof WebsiteIndexRoute
  '/_authenticated/admission/interviews': typeof AuthenticatedAdmissionInterviewsRoute
  '/_authenticated/admission/new': typeof AuthenticatedAdmissionNewRoute
  '/_authenticated/admission/queue': typeof AuthenticatedAdmissionQueueRoute
  '/_authenticated/finance_/donations': typeof AuthenticatedFinanceDonationsRoute
  '/_authenticated/madrassa/attendance': typeof AuthenticatedMadrassaAttendanceRoute
  '/_authenticated/madrassa/categories': typeof AuthenticatedMadrassaCategoriesRoute
  '/_authenticated/madrassa/classes': typeof AuthenticatedMadrassaClassesRoute
  '/_authenticated/madrassa/fees': typeof AuthenticatedMadrassaFeesRoute
  '/_authenticated/madrassa/hifz': typeof AuthenticatedMadrassaHifzRoute
  '/_authenticated/madrassa/students': typeof AuthenticatedMadrassaStudentsRoute
  '/_authenticated/madrassa/subjects': typeof AuthenticatedMadrassaSubjectsRoute
  '/_authenticated/madrassa/timetable': typeof AuthenticatedMadrassaTimetableRoute
  '/_authenticated/reports/annual': typeof AuthenticatedReportsAnnualRoute
  '/_authenticated/reports/attendance': typeof AuthenticatedReportsAttendanceRoute
  '/_authenticated/reports/category': typeof AuthenticatedReportsCategoryRoute
  '/_authenticated/reports/monthly': typeof AuthenticatedReportsMonthlyRoute
  '/_authenticated/school/attendance': typeof AuthenticatedSchoolAttendanceRoute
  '/_authenticated/school/classes': typeof AuthenticatedSchoolClassesRoute
  '/_authenticated/school/fees': typeof AuthenticatedSchoolFeesRoute
  '/_authenticated/school/students': typeof AuthenticatedSchoolStudentsRoute
  '/_authenticated/school/subjects': typeof AuthenticatedSchoolSubjectsRoute
  '/_authenticated/school/timetable': typeof AuthenticatedSchoolTimetableRoute
  '/_authenticated/settings/academic-year': typeof AuthenticatedSettingsAcademicYearRoute
  '/_authenticated/settings/backup': typeof AuthenticatedSettingsBackupRoute
  '/_authenticated/settings/concessions': typeof AuthenticatedSettingsConcessionsRoute
  '/_authenticated/settings/templates': typeof AuthenticatedSettingsTemplatesRoute
  '/_authenticated/settings/website': typeof AuthenticatedSettingsWebsiteRoute
  '/_authenticated/students/$id': typeof AuthenticatedStudentsIdRoute
  '/_authenticated/teachers/$id': typeof AuthenticatedTeachersIdRoute
  '/_authenticated/teachers_/salary': typeof AuthenticatedTeachersSalaryRoute
  '/_authenticated/admission/': typeof AuthenticatedAdmissionIndexRoute
  '/_authenticated/finance/': typeof AuthenticatedFinanceIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/teachers/': typeof AuthenticatedTeachersIndexRoute
  '/_authenticated/madrassa/exams/board': typeof AuthenticatedMadrassaExamsBoardRoute
  '/_authenticated/school/exams/board': typeof AuthenticatedSchoolExamsBoardRoute
  '/_authenticated/madrassa/exams/': typeof AuthenticatedMadrassaExamsIndexRoute
  '/_authenticated/school/exams/': typeof AuthenticatedSchoolExamsIndexRoute
  '/_authenticated/madrassa/exams/$id/marks': typeof AuthenticatedMadrassaExamsIdMarksRoute
  '/_authenticated/madrassa/exams/$id/results': typeof AuthenticatedMadrassaExamsIdResultsRoute
  '/_authenticated/madrassa/exams/$id/seating': typeof AuthenticatedMadrassaExamsIdSeatingRoute
  '/_authenticated/school/exams/$id/results': typeof AuthenticatedSchoolExamsIdResultsRoute
  '/_authenticated/school/exams/$id/seating': typeof AuthenticatedSchoolExamsIdSeatingRoute
  '/_authenticated/madrassa/exams/$id/': typeof AuthenticatedMadrassaExamsIdIndexRoute
  '/_authenticated/school/exams/$id/': typeof AuthenticatedSchoolExamsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/change-password'
    | '/login'
    | '/website'
    | '/audit'
    | '/dashboard'
    | '/holidays'
    | '/id-cards'
    | '/inventory'
    | '/notifications'
    | '/parents'
    | '/users'
    | '/website/contact'
    | '/website/gallery'
    | '/website/'
    | '/admission/interviews'
    | '/admission/new'
    | '/admission/queue'
    | '/finance/donations'
    | '/madrassa/attendance'
    | '/madrassa/categories'
    | '/madrassa/classes'
    | '/madrassa/fees'
    | '/madrassa/hifz'
    | '/madrassa/students'
    | '/madrassa/subjects'
    | '/madrassa/timetable'
    | '/reports/annual'
    | '/reports/attendance'
    | '/reports/category'
    | '/reports/monthly'
    | '/school/attendance'
    | '/school/classes'
    | '/school/fees'
    | '/school/students'
    | '/school/subjects'
    | '/school/timetable'
    | '/settings/academic-year'
    | '/settings/backup'
    | '/settings/concessions'
    | '/settings/templates'
    | '/settings/website'
    | '/students/$id'
    | '/teachers/$id'
    | '/teachers/salary'
    | '/admission/'
    | '/finance/'
    | '/reports/'
    | '/settings/'
    | '/teachers/'
    | '/madrassa/exams/board'
    | '/school/exams/board'
    | '/madrassa/exams/'
    | '/school/exams/'
    | '/madrassa/exams/$id/marks'
    | '/madrassa/exams/$id/results'
    | '/madrassa/exams/$id/seating'
    | '/school/exams/$id/results'
    | '/school/exams/$id/seating'
    | '/madrassa/exams/$id/'
    | '/school/exams/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/change-password'
    | '/login'
    | '/audit'
    | '/dashboard'
    | '/holidays'
    | '/id-cards'
    | '/inventory'
    | '/notifications'
    | '/parents'
    | '/users'
    | '/website/contact'
    | '/website/gallery'
    | '/website'
    | '/admission/interviews'
    | '/admission/new'
    | '/admission/queue'
    | '/finance/donations'
    | '/madrassa/attendance'
    | '/madrassa/categories'
    | '/madrassa/classes'
    | '/madrassa/fees'
    | '/madrassa/hifz'
    | '/madrassa/students'
    | '/madrassa/subjects'
    | '/madrassa/timetable'
    | '/reports/annual'
    | '/reports/attendance'
    | '/reports/category'
    | '/reports/monthly'
    | '/school/attendance'
    | '/school/classes'
    | '/school/fees'
    | '/school/students'
    | '/school/subjects'
    | '/school/timetable'
    | '/settings/academic-year'
    | '/settings/backup'
    | '/settings/concessions'
    | '/settings/templates'
    | '/settings/website'
    | '/students/$id'
    | '/teachers/$id'
    | '/teachers/salary'
    | '/admission'
    | '/finance'
    | '/reports'
    | '/settings'
    | '/teachers'
    | '/madrassa/exams/board'
    | '/school/exams/board'
    | '/madrassa/exams'
    | '/school/exams'
    | '/madrassa/exams/$id/marks'
    | '/madrassa/exams/$id/results'
    | '/madrassa/exams/$id/seating'
    | '/school/exams/$id/results'
    | '/school/exams/$id/seating'
    | '/madrassa/exams/$id'
    | '/school/exams/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/apply'
    | '/change-password'
    | '/login'
    | '/website'
    | '/_authenticated/audit'
    | '/_authenticated/dashboard'
    | '/_authenticated/holidays'
    | '/_authenticated/id-cards'
    | '/_authenticated/inventory'
    | '/_authenticated/notifications'
    | '/_authenticated/parents'
    | '/_authenticated/users'
    | '/website/contact'
    | '/website/gallery'
    | '/website/'
    | '/_authenticated/admission/interviews'
    | '/_authenticated/admission/new'
    | '/_authenticated/admission/queue'
    | '/_authenticated/finance_/donations'
    | '/_authenticated/madrassa/attendance'
    | '/_authenticated/madrassa/categories'
    | '/_authenticated/madrassa/classes'
    | '/_authenticated/madrassa/fees'
    | '/_authenticated/madrassa/hifz'
    | '/_authenticated/madrassa/students'
    | '/_authenticated/madrassa/subjects'
    | '/_authenticated/madrassa/timetable'
    | '/_authenticated/reports/annual'
    | '/_authenticated/reports/attendance'
    | '/_authenticated/reports/category'
    | '/_authenticated/reports/monthly'
    | '/_authenticated/school/attendance'
    | '/_authenticated/school/classes'
    | '/_authenticated/school/fees'
    | '/_authenticated/school/students'
    | '/_authenticated/school/subjects'
    | '/_authenticated/school/timetable'
    | '/_authenticated/settings/academic-year'
    | '/_authenticated/settings/backup'
    | '/_authenticated/settings/concessions'
    | '/_authenticated/settings/templates'
    | '/_authenticated/settings/website'
    | '/_authenticated/students/$id'
    | '/_authenticated/teachers/$id'
    | '/_authenticated/teachers_/salary'
    | '/_authenticated/admission/'
    | '/_authenticated/finance/'
    | '/_authenticated/reports/'
    | '/_authenticated/settings/'
    | '/_authenticated/teachers/'
    | '/_authenticated/madrassa/exams/board'
    | '/_authenticated/school/exams/board'
    | '/_authenticated/madrassa/exams/'
    | '/_authenticated/school/exams/'
    | '/_authenticated/madrassa/exams/$id/marks'
    | '/_authenticated/madrassa/exams/$id/results'
    | '/_authenticated/madrassa/exams/$id/seating'
    | '/_authenticated/school/exams/$id/results'
    | '/_authenticated/school/exams/$id/seating'
    | '/_authenticated/madrassa/exams/$id/'
    | '/_authenticated/school/exams/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
  WebsiteRoute: typeof WebsiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/website': {
      id: '/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof WebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website/': {
      id: '/website/'
      path: '/'
      fullPath: '/website/'
      preLoaderRoute: typeof WebsiteIndexRouteImport
      parentRoute: typeof WebsiteRoute
    }
    '/website/gallery': {
      id: '/website/gallery'
      path: '/gallery'
      fullPath: '/website/gallery'
      preLoaderRoute: typeof WebsiteGalleryRouteImport
      parentRoute: typeof WebsiteRoute
    }
    '/website/contact': {
      id: '/website/contact'
      path: '/contact'
      fullPath: '/website/contact'
      preLoaderRoute: typeof WebsiteContactRouteImport
      parentRoute: typeof WebsiteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parents': {
      id: '/_authenticated/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof AuthenticatedParentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/id-cards': {
      id: '/_authenticated/id-cards'
      path: '/id-cards'
      fullPath: '/id-cards'
      preLoaderRoute: typeof AuthenticatedIdCardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/holidays': {
      id: '/_authenticated/holidays'
      path: '/holidays'
      fullPath: '/holidays'
      preLoaderRoute: typeof AuthenticatedHolidaysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teachers/': {
      id: '/_authenticated/teachers/'
      path: '/teachers'
      fullPath: '/teachers/'
      preLoaderRoute: typeof AuthenticatedTeachersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance/': {
      id: '/_authenticated/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof AuthenticatedFinanceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admission/': {
      id: '/_authenticated/admission/'
      path: '/admission'
      fullPath: '/admission/'
      preLoaderRoute: typeof AuthenticatedAdmissionIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teachers_/salary': {
      id: '/_authenticated/teachers_/salary'
      path: '/teachers/salary'
      fullPath: '/teachers/salary'
      preLoaderRoute: typeof AuthenticatedTeachersSalaryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teachers/$id': {
      id: '/_authenticated/teachers/$id'
      path: '/teachers/$id'
      fullPath: '/teachers/$id'
      preLoaderRoute: typeof AuthenticatedTeachersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students/$id': {
      id: '/_authenticated/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AuthenticatedStudentsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/website': {
      id: '/_authenticated/settings/website'
      path: '/settings/website'
      fullPath: '/settings/website'
      preLoaderRoute: typeof AuthenticatedSettingsWebsiteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/templates': {
      id: '/_authenticated/settings/templates'
      path: '/settings/templates'
      fullPath: '/settings/templates'
      preLoaderRoute: typeof AuthenticatedSettingsTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/concessions': {
      id: '/_authenticated/settings/concessions'
      path: '/settings/concessions'
      fullPath: '/settings/concessions'
      preLoaderRoute: typeof AuthenticatedSettingsConcessionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/backup': {
      id: '/_authenticated/settings/backup'
      path: '/settings/backup'
      fullPath: '/settings/backup'
      preLoaderRoute: typeof AuthenticatedSettingsBackupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/academic-year': {
      id: '/_authenticated/settings/academic-year'
      path: '/settings/academic-year'
      fullPath: '/settings/academic-year'
      preLoaderRoute: typeof AuthenticatedSettingsAcademicYearRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/school/timetable': {
      id: '/_authenticated/school/timetable'
      path: '/school/timetable'
      fullPath: '/school/timetable'
      preLoaderRoute: typeof AuthenticatedSchoolTimetableRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/school/subjects': {
      id: '/_authenticated/school/subjects'
      path: '/school/subjects'
      fullPath: '/school/subjects'
      preLoaderRoute: typeof AuthenticatedSchoolSubjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/school/students': {
      id: '/_authenticated/school/students'
      path: '/school/students'
      fullPath: '/school/students'
      preLoaderRoute: typeof AuthenticatedSchoolStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/school/fees': {
      id: '/_authenticated/school/fees'
      path: '/school/fees'
      fullPath: '/school/fees'
      preLoaderRoute: typeof AuthenticatedSchoolFeesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/school/classes': {
      id: '/_authenticated/school/classes'
      path: '/school/classes'
      fullPath: '/school/classes'
      preLoaderRoute: typeof AuthenticatedSchoolClassesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/school/attendance': {
      id: '/_authenticated/school/attendance'
      path: '/school/attendance'
      fullPath: '/school/attendance'
      preLoaderRoute: typeof AuthenticatedSchoolAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/monthly': {
      id: '/_authenticated/reports/monthly'
      path: '/reports/monthly'
      fullPath: '/reports/monthly'
      preLoaderRoute: typeof AuthenticatedReportsMonthlyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/category': {
      id: '/_authenticated/reports/category'
      path: '/reports/category'
      fullPath: '/reports/category'
      preLoaderRoute: typeof AuthenticatedReportsCategoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/attendance': {
      id: '/_authenticated/reports/attendance'
      path: '/reports/attendance'
      fullPath: '/reports/attendance'
      preLoaderRoute: typeof AuthenticatedReportsAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/annual': {
      id: '/_authenticated/reports/annual'
      path: '/reports/annual'
      fullPath: '/reports/annual'
      preLoaderRoute: typeof AuthenticatedReportsAnnualRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/madrassa/timetable': {
      id: '/_authenticated/madrassa/timetable'
      path: '/madrassa/timetable'
      fullPath: '/madrassa/timetable'
      preLoaderRoute: typeof AuthenticatedMadrassaTimetableRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/madrassa/subjects': {
      id: '/_authenticated/madrassa/subjects'
      path: '/madrassa/subjects'
      fullPath: '/madrassa/subjects'
      preLoaderRoute: typeof AuthenticatedMadrassaSubjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/madrassa/students': {
      id: '/_authenticated/madrassa/students'
      path: '/madrassa/students'
      fullPath: '/madrassa/students'
      preLoaderRoute: typeof AuthenticatedMadrassaStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/madrassa/hifz': {
      id: '/_authenticated/madrassa/hifz'
      path: '/madrassa/hifz'
      fullPath: '/madrassa/hifz'
      preLoaderRoute: typeof AuthenticatedMadrassaHifzRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/madrassa/fees': {
      id: '/_authenticated/madrassa/fees'
      path: '/madrassa/fees'
      fullPath: '/madrassa/fees'
      preLoaderRoute: typeof AuthenticatedMadrassaFeesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/madrassa/classes': {
      id: '/_authenticated/madrassa/classes'
      path: '/madrassa/classes'
      fullPath: '/madrassa/classes'
      preLoaderRoute: typeof AuthenticatedMadrassaClassesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/madrassa/categories': {
      id: '/_authenticated/madrassa/categories'
      path: '/madrassa/categories'
      fullPath: '/madrassa/categories'
      preLoaderRoute: typeof AuthenticatedMadrassaCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/madrassa/attendance': {
      id: '/_authenticated/madrassa/attendance'
      path: '/madrassa/attendance'
      fullPath: '/madrassa/attendance'
      preLoaderRoute: typeof AuthenticatedMadrassaAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance_/donations': {
      id: '/_authenticated/finance_/donations'
      path: '/finance/donations'
      fullPath: '/finance/donations'
      preLoaderRoute: typeof AuthenticatedFinanceDonationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admission/queue': {
      id: '/_authenticated/admission/queue'
      path: '/admission/queue'
      fullPath: '/admission/queue'
      preLoaderRoute: typeof AuthenticatedAdmissionQueueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admission/new': {
      id: '/_authenticated/admission/new'
      path: '/admission/new'
      fullPath: '/admission/new'
      preLoaderRoute: typeof AuthenticatedAdmissionNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admission/interviews': {
      id: '/_authenticated/admission/interviews'
      path: '/admission/interviews'
      fullPath: '/admission/interviews'
      preLoaderRoute: typeof AuthenticatedAdmissionInterviewsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/school/exams/': {
      id: '/_authenticated/school/exams/'
      path: '/school/exams'
      fullPath: '/school/exams/'
      preLoaderRoute: typeof AuthenticatedSchoolExamsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/madrassa/exams/': {
      id: '/_authenticated/madrassa/exams/'
      path: '/madrassa/exams'
      fullPath: '/madrassa/exams/'
      preLoaderRoute: typeof AuthenticatedMadrassaExamsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/school/exams/board': {
      id: '/_authenticated/school/exams/board'
      path: '/school/exams/board'
      fullPath: '/school/exams/board'
      preLoaderRoute: typeof AuthenticatedSchoolExamsBoardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/madrassa/exams/board': {
      id: '/_authenticated/madrassa/exams/board'
      path: '/madrassa/exams/board'
      fullPath: '/madrassa/exams/board'
      preLoaderRoute: typeof AuthenticatedMadrassaExamsBoardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/school/exams/$id/': {
      id: '/_authenticated/school/exams/$id/'
      path: '/school/exams/$id'
      fullPath: '/school/exams/$id/'
      preLoaderRoute: typeof AuthenticatedSchoolExamsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/madrassa/exams/$id/': {
      id: '/_authenticated/madrassa/exams/$id/'
      path: '/madrassa/exams/$id'
      fullPath: '/madrassa/exams/$id/'
      preLoaderRoute: typeof AuthenticatedMadrassaExamsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/school/exams/$id/seating': {
      id: '/_authenticated/school/exams/$id/seating'
      path: '/school/exams/$id/seating'
      fullPath: '/school/exams/$id/seating'
      preLoaderRoute: typeof AuthenticatedSchoolExamsIdSeatingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/school/exams/$id/results': {
      id: '/_authenticated/school/exams/$id/results'
      path: '/school/exams/$id/results'
      fullPath: '/school/exams/$id/results'
      preLoaderRoute: typeof AuthenticatedSchoolExamsIdResultsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/madrassa/exams/$id/seating': {
      id: '/_authenticated/madrassa/exams/$id/seating'
      path: '/madrassa/exams/$id/seating'
      fullPath: '/madrassa/exams/$id/seating'
      preLoaderRoute: typeof AuthenticatedMadrassaExamsIdSeatingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/madrassa/exams/$id/results': {
      id: '/_authenticated/madrassa/exams/$id/results'
      path: '/madrassa/exams/$id/results'
      fullPath: '/madrassa/exams/$id/results'
      preLoaderRoute: typeof AuthenticatedMadrassaExamsIdResultsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/madrassa/exams/$id/marks': {
      id: '/_authenticated/madrassa/exams/$id/marks'
      path: '/madrassa/exams/$id/marks'
      fullPath: '/madrassa/exams/$id/marks'
      preLoaderRoute: typeof AuthenticatedMadrassaExamsIdMarksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHolidaysRoute: typeof AuthenticatedHolidaysRoute
  AuthenticatedIdCardsRoute: typeof AuthenticatedIdCardsRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedParentsRoute: typeof AuthenticatedParentsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedAdmissionInterviewsRoute: typeof AuthenticatedAdmissionInterviewsRoute
  AuthenticatedAdmissionNewRoute: typeof AuthenticatedAdmissionNewRoute
  AuthenticatedAdmissionQueueRoute: typeof AuthenticatedAdmissionQueueRoute
  AuthenticatedFinanceDonationsRoute: typeof AuthenticatedFinanceDonationsRoute
  AuthenticatedMadrassaAttendanceRoute: typeof AuthenticatedMadrassaAttendanceRoute
  AuthenticatedMadrassaCategoriesRoute: typeof AuthenticatedMadrassaCategoriesRoute
  AuthenticatedMadrassaClassesRoute: typeof AuthenticatedMadrassaClassesRoute
  AuthenticatedMadrassaFeesRoute: typeof AuthenticatedMadrassaFeesRoute
  AuthenticatedMadrassaHifzRoute: typeof AuthenticatedMadrassaHifzRoute
  AuthenticatedMadrassaStudentsRoute: typeof AuthenticatedMadrassaStudentsRoute
  AuthenticatedMadrassaSubjectsRoute: typeof AuthenticatedMadrassaSubjectsRoute
  AuthenticatedMadrassaTimetableRoute: typeof AuthenticatedMadrassaTimetableRoute
  AuthenticatedReportsAnnualRoute: typeof AuthenticatedReportsAnnualRoute
  AuthenticatedReportsAttendanceRoute: typeof AuthenticatedReportsAttendanceRoute
  AuthenticatedReportsCategoryRoute: typeof AuthenticatedReportsCategoryRoute
  AuthenticatedReportsMonthlyRoute: typeof AuthenticatedReportsMonthlyRoute
  AuthenticatedSchoolAttendanceRoute: typeof AuthenticatedSchoolAttendanceRoute
  AuthenticatedSchoolClassesRoute: typeof AuthenticatedSchoolClassesRoute
  AuthenticatedSchoolFeesRoute: typeof AuthenticatedSchoolFeesRoute
  AuthenticatedSchoolStudentsRoute: typeof AuthenticatedSchoolStudentsRoute
  AuthenticatedSchoolSubjectsRoute: typeof AuthenticatedSchoolSubjectsRoute
  AuthenticatedSchoolTimetableRoute: typeof AuthenticatedSchoolTimetableRoute
  AuthenticatedSettingsAcademicYearRoute: typeof AuthenticatedSettingsAcademicYearRoute
  AuthenticatedSettingsBackupRoute: typeof AuthenticatedSettingsBackupRoute
  AuthenticatedSettingsConcessionsRoute: typeof AuthenticatedSettingsConcessionsRoute
  AuthenticatedSettingsTemplatesRoute: typeof AuthenticatedSettingsTemplatesRoute
  AuthenticatedSettingsWebsiteRoute: typeof AuthenticatedSettingsWebsiteRoute
  AuthenticatedStudentsIdRoute: typeof AuthenticatedStudentsIdRoute
  AuthenticatedTeachersIdRoute: typeof AuthenticatedTeachersIdRoute
  AuthenticatedTeachersSalaryRoute: typeof AuthenticatedTeachersSalaryRoute
  AuthenticatedAdmissionIndexRoute: typeof AuthenticatedAdmissionIndexRoute
  AuthenticatedFinanceIndexRoute: typeof AuthenticatedFinanceIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedTeachersIndexRoute: typeof AuthenticatedTeachersIndexRoute
  AuthenticatedMadrassaExamsBoardRoute: typeof AuthenticatedMadrassaExamsBoardRoute
  AuthenticatedSchoolExamsBoardRoute: typeof AuthenticatedSchoolExamsBoardRoute
  AuthenticatedMadrassaExamsIndexRoute: typeof AuthenticatedMadrassaExamsIndexRoute
  AuthenticatedSchoolExamsIndexRoute: typeof AuthenticatedSchoolExamsIndexRoute
  AuthenticatedMadrassaExamsIdMarksRoute: typeof AuthenticatedMadrassaExamsIdMarksRoute
  AuthenticatedMadrassaExamsIdResultsRoute: typeof AuthenticatedMadrassaExamsIdResultsRoute
  AuthenticatedMadrassaExamsIdSeatingRoute: typeof AuthenticatedMadrassaExamsIdSeatingRoute
  AuthenticatedSchoolExamsIdResultsRoute: typeof AuthenticatedSchoolExamsIdResultsRoute
  AuthenticatedSchoolExamsIdSeatingRoute: typeof AuthenticatedSchoolExamsIdSeatingRoute
  AuthenticatedMadrassaExamsIdIndexRoute: typeof AuthenticatedMadrassaExamsIdIndexRoute
  AuthenticatedSchoolExamsIdIndexRoute: typeof AuthenticatedSchoolExamsIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHolidaysRoute: AuthenticatedHolidaysRoute,
  AuthenticatedIdCardsRoute: AuthenticatedIdCardsRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedParentsRoute: AuthenticatedParentsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedAdmissionInterviewsRoute: AuthenticatedAdmissionInterviewsRoute,
  AuthenticatedAdmissionNewRoute: AuthenticatedAdmissionNewRoute,
  AuthenticatedAdmissionQueueRoute: AuthenticatedAdmissionQueueRoute,
  AuthenticatedFinanceDonationsRoute: AuthenticatedFinanceDonationsRoute,
  AuthenticatedMadrassaAttendanceRoute: AuthenticatedMadrassaAttendanceRoute,
  AuthenticatedMadrassaCategoriesRoute: AuthenticatedMadrassaCategoriesRoute,
  AuthenticatedMadrassaClassesRoute: AuthenticatedMadrassaClassesRoute,
  AuthenticatedMadrassaFeesRoute: AuthenticatedMadrassaFeesRoute,
  AuthenticatedMadrassaHifzRoute: AuthenticatedMadrassaHifzRoute,
  AuthenticatedMadrassaStudentsRoute: AuthenticatedMadrassaStudentsRoute,
  AuthenticatedMadrassaSubjectsRoute: AuthenticatedMadrassaSubjectsRoute,
  AuthenticatedMadrassaTimetableRoute: AuthenticatedMadrassaTimetableRoute,
  AuthenticatedReportsAnnualRoute: AuthenticatedReportsAnnualRoute,
  AuthenticatedReportsAttendanceRoute: AuthenticatedReportsAttendanceRoute,
  AuthenticatedReportsCategoryRoute: AuthenticatedReportsCategoryRoute,
  AuthenticatedReportsMonthlyRoute: AuthenticatedReportsMonthlyRoute,
  AuthenticatedSchoolAttendanceRoute: AuthenticatedSchoolAttendanceRoute,
  AuthenticatedSchoolClassesRoute: AuthenticatedSchoolClassesRoute,
  AuthenticatedSchoolFeesRoute: AuthenticatedSchoolFeesRoute,
  AuthenticatedSchoolStudentsRoute: AuthenticatedSchoolStudentsRoute,
  AuthenticatedSchoolSubjectsRoute: AuthenticatedSchoolSubjectsRoute,
  AuthenticatedSchoolTimetableRoute: AuthenticatedSchoolTimetableRoute,
  AuthenticatedSettingsAcademicYearRoute:
    AuthenticatedSettingsAcademicYearRoute,
  AuthenticatedSettingsBackupRoute: AuthenticatedSettingsBackupRoute,
  AuthenticatedSettingsConcessionsRoute: AuthenticatedSettingsConcessionsRoute,
  AuthenticatedSettingsTemplatesRoute: AuthenticatedSettingsTemplatesRoute,
  AuthenticatedSettingsWebsiteRoute: AuthenticatedSettingsWebsiteRoute,
  AuthenticatedStudentsIdRoute: AuthenticatedStudentsIdRoute,
  AuthenticatedTeachersIdRoute: AuthenticatedTeachersIdRoute,
  AuthenticatedTeachersSalaryRoute: AuthenticatedTeachersSalaryRoute,
  AuthenticatedAdmissionIndexRoute: AuthenticatedAdmissionIndexRoute,
  AuthenticatedFinanceIndexRoute: AuthenticatedFinanceIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedTeachersIndexRoute: AuthenticatedTeachersIndexRoute,
  AuthenticatedMadrassaExamsBoardRoute: AuthenticatedMadrassaExamsBoardRoute,
  AuthenticatedSchoolExamsBoardRoute: AuthenticatedSchoolExamsBoardRoute,
  AuthenticatedMadrassaExamsIndexRoute: AuthenticatedMadrassaExamsIndexRoute,
  AuthenticatedSchoolExamsIndexRoute: AuthenticatedSchoolExamsIndexRoute,
  AuthenticatedMadrassaExamsIdMarksRoute:
    AuthenticatedMadrassaExamsIdMarksRoute,
  AuthenticatedMadrassaExamsIdResultsRoute:
    AuthenticatedMadrassaExamsIdResultsRoute,
  AuthenticatedMadrassaExamsIdSeatingRoute:
    AuthenticatedMadrassaExamsIdSeatingRoute,
  AuthenticatedSchoolExamsIdResultsRoute:
    AuthenticatedSchoolExamsIdResultsRoute,
  AuthenticatedSchoolExamsIdSeatingRoute:
    AuthenticatedSchoolExamsIdSeatingRoute,
  AuthenticatedMadrassaExamsIdIndexRoute:
    AuthenticatedMadrassaExamsIdIndexRoute,
  AuthenticatedSchoolExamsIdIndexRoute: AuthenticatedSchoolExamsIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface WebsiteRouteChildren {
  WebsiteContactRoute: typeof WebsiteContactRoute
  WebsiteGalleryRoute: typeof WebsiteGalleryRoute
  WebsiteIndexRoute: typeof WebsiteIndexRoute
}

const WebsiteRouteChildren: WebsiteRouteChildren = {
  WebsiteContactRoute: WebsiteContactRoute,
  WebsiteGalleryRoute: WebsiteGalleryRoute,
  WebsiteIndexRoute: WebsiteIndexRoute,
}

const WebsiteRouteWithChildren =
  WebsiteRoute._addFileChildren(WebsiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ApplyRoute: ApplyRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
  WebsiteRoute: WebsiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
