/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsiteRouteImport } from './routes/website'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WebsiteIndexRouteImport } from './routes/website.index'
import { Route as WebsiteGalleryRouteImport } from './routes/website.gallery'
import { Route as WebsiteContactRouteImport } from './routes/website.contact'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTeachersRouteImport } from './routes/_authenticated/teachers'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedParentsRouteImport } from './routes/_authenticated/parents'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedIdCardsRouteImport } from './routes/_authenticated/id-cards'
import { Route as AuthenticatedHolidaysRouteImport } from './routes/_authenticated/holidays'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedAdmissionIndexRouteImport } from './routes/_authenticated/admission/index'
import { Route as AuthenticatedTeachersSalaryRouteImport } from './routes/_authenticated/teachers.salary'
import { Route as AuthenticatedTeachersIdRouteImport } from './routes/_authenticated/teachers.$id'
import { Route as AuthenticatedStudentsIdRouteImport } from './routes/_authenticated/students.$id'
import { Route as AuthenticatedSettingsWebsiteRouteImport } from './routes/_authenticated/settings/website'
import { Route as AuthenticatedSettingsTemplatesRouteImport } from './routes/_authenticated/settings/templates'
import { Route as AuthenticatedSettingsConcessionsRouteImport } from './routes/_authenticated/settings/concessions'
import { Route as AuthenticatedSettingsAcademicYearRouteImport } from './routes/_authenticated/settings/academic-year'
import { Route as AuthenticatedSchoolTimetableRouteImport } from './routes/_authenticated/school/timetable'
import { Route as AuthenticatedSchoolSubjectsRouteImport } from './routes/_authenticated/school/subjects'
import { Route as AuthenticatedSchoolStudentsRouteImport } from './routes/_authenticated/school/students'
import { Route as AuthenticatedSchoolFeesRouteImport } from './routes/_authenticated/school/fees'
import { Route as AuthenticatedSchoolExamsRouteImport } from './routes/_authenticated/school/exams'
import { Route as AuthenticatedSchoolClassesRouteImport } from './routes/_authenticated/school/classes'
import { Route as AuthenticatedSchoolAttendanceRouteImport } from './routes/_authenticated/school/attendance'
import { Route as AuthenticatedReportsMonthlyRouteImport } from './routes/_authenticated/reports.monthly'
import { Route as AuthenticatedReportsCategoryRouteImport } from './routes/_authenticated/reports.category'
import { Route as AuthenticatedReportsAttendanceRouteImport } from './routes/_authenticated/reports.attendance'
import { Route as AuthenticatedReportsAnnualRouteImport } from './routes/_authenticated/reports.annual'
import { Route as AuthenticatedMadrassaTimetableRouteImport } from './routes/_authenticated/madrassa/timetable'
import { Route as AuthenticatedMadrassaSubjectsRouteImport } from './routes/_authenticated/madrassa/subjects'
import { Route as AuthenticatedMadrassaStudentsRouteImport } from './routes/_authenticated/madrassa/students'
import { Route as AuthenticatedMadrassaHifzRouteImport } from './routes/_authenticated/madrassa/hifz'
import { Route as AuthenticatedMadrassaFeesRouteImport } from './routes/_authenticated/madrassa/fees'
import { Route as AuthenticatedMadrassaExamsRouteImport } from './routes/_authenticated/madrassa/exams'
import { Route as AuthenticatedMadrassaClassesRouteImport } from './routes/_authenticated/madrassa/classes'
import { Route as AuthenticatedMadrassaCategoriesRouteImport } from './routes/_authenticated/madrassa/categories'
import { Route as AuthenticatedMadrassaAttendanceRouteImport } from './routes/_authenticated/madrassa/attendance'
import { Route as AuthenticatedFinanceDonationsRouteImport } from './routes/_authenticated/finance.donations'
import { Route as AuthenticatedAdmissionQueueRouteImport } from './routes/_authenticated/admission/queue'
import { Route as AuthenticatedAdmissionNewRouteImport } from './routes/_authenticated/admission/new'
import { Route as AuthenticatedSchoolExamsBoardRouteImport } from './routes/_authenticated/school/exams.board'
import { Route as AuthenticatedSchoolExamsIdRouteImport } from './routes/_authenticated/school/exams.$id'
import { Route as AuthenticatedMadrassaExamsBoardRouteImport } from './routes/_authenticated/madrassa/exams.board'
import { Route as AuthenticatedMadrassaExamsIdRouteImport } from './routes/_authenticated/madrassa/exams.$id'
import { Route as AuthenticatedSchoolExamsIdSeatingRouteImport } from './routes/_authenticated/school/exams.$id.seating'
import { Route as AuthenticatedSchoolExamsIdResultsRouteImport } from './routes/_authenticated/school/exams.$id.results'
import { Route as AuthenticatedMadrassaExamsIdResultsRouteImport } from './routes/_authenticated/madrassa/exams.$id.results'
import { Route as AuthenticatedMadrassaExamsIdMarksRouteImport } from './routes/_authenticated/madrassa/exams.$id.marks'

const WebsiteRoute = WebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteIndexRoute = WebsiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebsiteRoute,
} as any)
const WebsiteGalleryRoute = WebsiteGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => WebsiteRoute,
} as any)
const WebsiteContactRoute = WebsiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => WebsiteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeachersRoute = AuthenticatedTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedParentsRoute = AuthenticatedParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIdCardsRoute = AuthenticatedIdCardsRouteImport.update({
  id: '/id-cards',
  path: '/id-cards',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHolidaysRoute = AuthenticatedHolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdmissionIndexRoute =
  AuthenticatedAdmissionIndexRouteImport.update({
    id: '/admission/',
    path: '/admission/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeachersSalaryRoute =
  AuthenticatedTeachersSalaryRouteImport.update({
    id: '/salary',
    path: '/salary',
    getParentRoute: () => AuthenticatedTeachersRoute,
  } as any)
const AuthenticatedTeachersIdRoute = AuthenticatedTeachersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedTeachersRoute,
} as any)
const AuthenticatedStudentsIdRoute = AuthenticatedStudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsWebsiteRoute =
  AuthenticatedSettingsWebsiteRouteImport.update({
    id: '/settings/website',
    path: '/settings/website',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsTemplatesRoute =
  AuthenticatedSettingsTemplatesRouteImport.update({
    id: '/settings/templates',
    path: '/settings/templates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsConcessionsRoute =
  AuthenticatedSettingsConcessionsRouteImport.update({
    id: '/settings/concessions',
    path: '/settings/concessions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAcademicYearRoute =
  AuthenticatedSettingsAcademicYearRouteImport.update({
    id: '/settings/academic-year',
    path: '/settings/academic-year',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSchoolTimetableRoute =
  AuthenticatedSchoolTimetableRouteImport.update({
    id: '/school/timetable',
    path: '/school/timetable',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSchoolSubjectsRoute =
  AuthenticatedSchoolSubjectsRouteImport.update({
    id: '/school/subjects',
    path: '/school/subjects',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSchoolStudentsRoute =
  AuthenticatedSchoolStudentsRouteImport.update({
    id: '/school/students',
    path: '/school/students',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSchoolFeesRoute = AuthenticatedSchoolFeesRouteImport.update({
  id: '/school/fees',
  path: '/school/fees',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSchoolExamsRoute =
  AuthenticatedSchoolExamsRouteImport.update({
    id: '/school/exams',
    path: '/school/exams',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSchoolClassesRoute =
  AuthenticatedSchoolClassesRouteImport.update({
    id: '/school/classes',
    path: '/school/classes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSchoolAttendanceRoute =
  AuthenticatedSchoolAttendanceRouteImport.update({
    id: '/school/attendance',
    path: '/school/attendance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsMonthlyRoute =
  AuthenticatedReportsMonthlyRouteImport.update({
    id: '/monthly',
    path: '/monthly',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsCategoryRoute =
  AuthenticatedReportsCategoryRouteImport.update({
    id: '/category',
    path: '/category',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsAttendanceRoute =
  AuthenticatedReportsAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsAnnualRoute =
  AuthenticatedReportsAnnualRouteImport.update({
    id: '/annual',
    path: '/annual',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedMadrassaTimetableRoute =
  AuthenticatedMadrassaTimetableRouteImport.update({
    id: '/madrassa/timetable',
    path: '/madrassa/timetable',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMadrassaSubjectsRoute =
  AuthenticatedMadrassaSubjectsRouteImport.update({
    id: '/madrassa/subjects',
    path: '/madrassa/subjects',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMadrassaStudentsRoute =
  AuthenticatedMadrassaStudentsRouteImport.update({
    id: '/madrassa/students',
    path: '/madrassa/students',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMadrassaHifzRoute =
  AuthenticatedMadrassaHifzRouteImport.update({
    id: '/madrassa/hifz',
    path: '/madrassa/hifz',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMadrassaFeesRoute =
  AuthenticatedMadrassaFeesRouteImport.update({
    id: '/madrassa/fees',
    path: '/madrassa/fees',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMadrassaExamsRoute =
  AuthenticatedMadrassaExamsRouteImport.update({
    id: '/madrassa/exams',
    path: '/madrassa/exams',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMadrassaClassesRoute =
  AuthenticatedMadrassaClassesRouteImport.update({
    id: '/madrassa/classes',
    path: '/madrassa/classes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMadrassaCategoriesRoute =
  AuthenticatedMadrassaCategoriesRouteImport.update({
    id: '/madrassa/categories',
    path: '/madrassa/categories',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMadrassaAttendanceRoute =
  AuthenticatedMadrassaAttendanceRouteImport.update({
    id: '/madrassa/attendance',
    path: '/madrassa/attendance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceDonationsRoute =
  AuthenticatedFinanceDonationsRouteImport.update({
    id: '/donations',
    path: '/donations',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedAdmissionQueueRoute =
  AuthenticatedAdmissionQueueRouteImport.update({
    id: '/admission/queue',
    path: '/admission/queue',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdmissionNewRoute =
  AuthenticatedAdmissionNewRouteImport.update({
    id: '/admission/new',
    path: '/admission/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSchoolExamsBoardRoute =
  AuthenticatedSchoolExamsBoardRouteImport.update({
    id: '/board',
    path: '/board',
    getParentRoute: () => AuthenticatedSchoolExamsRoute,
  } as any)
const AuthenticatedSchoolExamsIdRoute =
  AuthenticatedSchoolExamsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedSchoolExamsRoute,
  } as any)
const AuthenticatedMadrassaExamsBoardRoute =
  AuthenticatedMadrassaExamsBoardRouteImport.update({
    id: '/board',
    path: '/board',
    getParentRoute: () => AuthenticatedMadrassaExamsRoute,
  } as any)
const AuthenticatedMadrassaExamsIdRoute =
  AuthenticatedMadrassaExamsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedMadrassaExamsRoute,
  } as any)
const AuthenticatedSchoolExamsIdSeatingRoute =
  AuthenticatedSchoolExamsIdSeatingRouteImport.update({
    id: '/seating',
    path: '/seating',
    getParentRoute: () => AuthenticatedSchoolExamsIdRoute,
  } as any)
const AuthenticatedSchoolExamsIdResultsRoute =
  AuthenticatedSchoolExamsIdResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => AuthenticatedSchoolExamsIdRoute,
  } as any)
const AuthenticatedMadrassaExamsIdResultsRoute =
  AuthenticatedMadrassaExamsIdResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => AuthenticatedMadrassaExamsIdRoute,
  } as any)
const AuthenticatedMadrassaExamsIdMarksRoute =
  AuthenticatedMadrassaExamsIdMarksRouteImport.update({
    id: '/marks',
    path: '/marks',
    getParentRoute: () => AuthenticatedMadrassaExamsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/website': typeof WebsiteRouteWithChildren
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/holidays': typeof AuthenticatedHolidaysRoute
  '/id-cards': typeof AuthenticatedIdCardsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/parents': typeof AuthenticatedParentsRoute
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/teachers': typeof AuthenticatedTeachersRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/website/contact': typeof WebsiteContactRoute
  '/website/gallery': typeof WebsiteGalleryRoute
  '/website/': typeof WebsiteIndexRoute
  '/admission/new': typeof AuthenticatedAdmissionNewRoute
  '/admission/queue': typeof AuthenticatedAdmissionQueueRoute
  '/finance/donations': typeof AuthenticatedFinanceDonationsRoute
  '/madrassa/attendance': typeof AuthenticatedMadrassaAttendanceRoute
  '/madrassa/categories': typeof AuthenticatedMadrassaCategoriesRoute
  '/madrassa/classes': typeof AuthenticatedMadrassaClassesRoute
  '/madrassa/exams': typeof AuthenticatedMadrassaExamsRouteWithChildren
  '/madrassa/fees': typeof AuthenticatedMadrassaFeesRoute
  '/madrassa/hifz': typeof AuthenticatedMadrassaHifzRoute
  '/madrassa/students': typeof AuthenticatedMadrassaStudentsRoute
  '/madrassa/subjects': typeof AuthenticatedMadrassaSubjectsRoute
  '/madrassa/timetable': typeof AuthenticatedMadrassaTimetableRoute
  '/reports/annual': typeof AuthenticatedReportsAnnualRoute
  '/reports/attendance': typeof AuthenticatedReportsAttendanceRoute
  '/reports/category': typeof AuthenticatedReportsCategoryRoute
  '/reports/monthly': typeof AuthenticatedReportsMonthlyRoute
  '/school/attendance': typeof AuthenticatedSchoolAttendanceRoute
  '/school/classes': typeof AuthenticatedSchoolClassesRoute
  '/school/exams': typeof AuthenticatedSchoolExamsRouteWithChildren
  '/school/fees': typeof AuthenticatedSchoolFeesRoute
  '/school/students': typeof AuthenticatedSchoolStudentsRoute
  '/school/subjects': typeof AuthenticatedSchoolSubjectsRoute
  '/school/timetable': typeof AuthenticatedSchoolTimetableRoute
  '/settings/academic-year': typeof AuthenticatedSettingsAcademicYearRoute
  '/settings/concessions': typeof AuthenticatedSettingsConcessionsRoute
  '/settings/templates': typeof AuthenticatedSettingsTemplatesRoute
  '/settings/website': typeof AuthenticatedSettingsWebsiteRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/teachers/$id': typeof AuthenticatedTeachersIdRoute
  '/teachers/salary': typeof AuthenticatedTeachersSalaryRoute
  '/admission/': typeof AuthenticatedAdmissionIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/madrassa/exams/$id': typeof AuthenticatedMadrassaExamsIdRouteWithChildren
  '/madrassa/exams/board': typeof AuthenticatedMadrassaExamsBoardRoute
  '/school/exams/$id': typeof AuthenticatedSchoolExamsIdRouteWithChildren
  '/school/exams/board': typeof AuthenticatedSchoolExamsBoardRoute
  '/madrassa/exams/$id/marks': typeof AuthenticatedMadrassaExamsIdMarksRoute
  '/madrassa/exams/$id/results': typeof AuthenticatedMadrassaExamsIdResultsRoute
  '/school/exams/$id/results': typeof AuthenticatedSchoolExamsIdResultsRoute
  '/school/exams/$id/seating': typeof AuthenticatedSchoolExamsIdSeatingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/holidays': typeof AuthenticatedHolidaysRoute
  '/id-cards': typeof AuthenticatedIdCardsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/parents': typeof AuthenticatedParentsRoute
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/teachers': typeof AuthenticatedTeachersRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/website/contact': typeof WebsiteContactRoute
  '/website/gallery': typeof WebsiteGalleryRoute
  '/website': typeof WebsiteIndexRoute
  '/admission/new': typeof AuthenticatedAdmissionNewRoute
  '/admission/queue': typeof AuthenticatedAdmissionQueueRoute
  '/finance/donations': typeof AuthenticatedFinanceDonationsRoute
  '/madrassa/attendance': typeof AuthenticatedMadrassaAttendanceRoute
  '/madrassa/categories': typeof AuthenticatedMadrassaCategoriesRoute
  '/madrassa/classes': typeof AuthenticatedMadrassaClassesRoute
  '/madrassa/exams': typeof AuthenticatedMadrassaExamsRouteWithChildren
  '/madrassa/fees': typeof AuthenticatedMadrassaFeesRoute
  '/madrassa/hifz': typeof AuthenticatedMadrassaHifzRoute
  '/madrassa/students': typeof AuthenticatedMadrassaStudentsRoute
  '/madrassa/subjects': typeof AuthenticatedMadrassaSubjectsRoute
  '/madrassa/timetable': typeof AuthenticatedMadrassaTimetableRoute
  '/reports/annual': typeof AuthenticatedReportsAnnualRoute
  '/reports/attendance': typeof AuthenticatedReportsAttendanceRoute
  '/reports/category': typeof AuthenticatedReportsCategoryRoute
  '/reports/monthly': typeof AuthenticatedReportsMonthlyRoute
  '/school/attendance': typeof AuthenticatedSchoolAttendanceRoute
  '/school/classes': typeof AuthenticatedSchoolClassesRoute
  '/school/exams': typeof AuthenticatedSchoolExamsRouteWithChildren
  '/school/fees': typeof AuthenticatedSchoolFeesRoute
  '/school/students': typeof AuthenticatedSchoolStudentsRoute
  '/school/subjects': typeof AuthenticatedSchoolSubjectsRoute
  '/school/timetable': typeof AuthenticatedSchoolTimetableRoute
  '/settings/academic-year': typeof AuthenticatedSettingsAcademicYearRoute
  '/settings/concessions': typeof AuthenticatedSettingsConcessionsRoute
  '/settings/templates': typeof AuthenticatedSettingsTemplatesRoute
  '/settings/website': typeof AuthenticatedSettingsWebsiteRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/teachers/$id': typeof AuthenticatedTeachersIdRoute
  '/teachers/salary': typeof AuthenticatedTeachersSalaryRoute
  '/admission': typeof AuthenticatedAdmissionIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/madrassa/exams/$id': typeof AuthenticatedMadrassaExamsIdRouteWithChildren
  '/madrassa/exams/board': typeof AuthenticatedMadrassaExamsBoardRoute
  '/school/exams/$id': typeof AuthenticatedSchoolExamsIdRouteWithChildren
  '/school/exams/board': typeof AuthenticatedSchoolExamsBoardRoute
  '/madrassa/exams/$id/marks': typeof AuthenticatedMadrassaExamsIdMarksRoute
  '/madrassa/exams/$id/results': typeof AuthenticatedMadrassaExamsIdResultsRoute
  '/school/exams/$id/results': typeof AuthenticatedSchoolExamsIdResultsRoute
  '/school/exams/$id/seating': typeof AuthenticatedSchoolExamsIdSeatingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/apply': typeof ApplyRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/website': typeof WebsiteRouteWithChildren
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/_authenticated/holidays': typeof AuthenticatedHolidaysRoute
  '/_authenticated/id-cards': typeof AuthenticatedIdCardsRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/parents': typeof AuthenticatedParentsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/teachers': typeof AuthenticatedTeachersRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/website/contact': typeof WebsiteContactRoute
  '/website/gallery': typeof WebsiteGalleryRoute
  '/website/': typeof WebsiteIndexRoute
  '/_authenticated/admission/new': typeof AuthenticatedAdmissionNewRoute
  '/_authenticated/admission/queue': typeof AuthenticatedAdmissionQueueRoute
  '/_authenticated/finance/donations': typeof AuthenticatedFinanceDonationsRoute
  '/_authenticated/madrassa/attendance': typeof AuthenticatedMadrassaAttendanceRoute
  '/_authenticated/madrassa/categories': typeof AuthenticatedMadrassaCategoriesRoute
  '/_authenticated/madrassa/classes': typeof AuthenticatedMadrassaClassesRoute
  '/_authenticated/madrassa/exams': typeof AuthenticatedMadrassaExamsRouteWithChildren
  '/_authenticated/madrassa/fees': typeof AuthenticatedMadrassaFeesRoute
  '/_authenticated/madrassa/hifz': typeof AuthenticatedMadrassaHifzRoute
  '/_authenticated/madrassa/students': typeof AuthenticatedMadrassaStudentsRoute
  '/_authenticated/madrassa/subjects': typeof AuthenticatedMadrassaSubjectsRoute
  '/_authenticated/madrassa/timetable': typeof AuthenticatedMadrassaTimetableRoute
  '/_authenticated/reports/annual': typeof AuthenticatedReportsAnnualRoute
  '/_authenticated/reports/attendance': typeof AuthenticatedReportsAttendanceRoute
  '/_authenticated/reports/category': typeof AuthenticatedReportsCategoryRoute
  '/_authenticated/reports/monthly': typeof AuthenticatedReportsMonthlyRoute
  '/_authenticated/school/attendance': typeof AuthenticatedSchoolAttendanceRoute
  '/_authenticated/school/classes': typeof AuthenticatedSchoolClassesRoute
  '/_authenticated/school/exams': typeof AuthenticatedSchoolExamsRouteWithChildren
  '/_authenticated/school/fees': typeof AuthenticatedSchoolFeesRoute
  '/_authenticated/school/students': typeof AuthenticatedSchoolStudentsRoute
  '/_authenticated/school/subjects': typeof AuthenticatedSchoolSubjectsRoute
  '/_authenticated/school/timetable': typeof AuthenticatedSchoolTimetableRoute
  '/_authenticated/settings/academic-year': typeof AuthenticatedSettingsAcademicYearRoute
  '/_authenticated/settings/concessions': typeof AuthenticatedSettingsConcessionsRoute
  '/_authenticated/settings/templates': typeof AuthenticatedSettingsTemplatesRoute
  '/_authenticated/settings/website': typeof AuthenticatedSettingsWebsiteRoute
  '/_authenticated/students/$id': typeof AuthenticatedStudentsIdRoute
  '/_authenticated/teachers/$id': typeof AuthenticatedTeachersIdRoute
  '/_authenticated/teachers/salary': typeof AuthenticatedTeachersSalaryRoute
  '/_authenticated/admission/': typeof AuthenticatedAdmissionIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/madrassa/exams/$id': typeof AuthenticatedMadrassaExamsIdRouteWithChildren
  '/_authenticated/madrassa/exams/board': typeof AuthenticatedMadrassaExamsBoardRoute
  '/_authenticated/school/exams/$id': typeof AuthenticatedSchoolExamsIdRouteWithChildren
  '/_authenticated/school/exams/board': typeof AuthenticatedSchoolExamsBoardRoute
  '/_authenticated/madrassa/exams/$id/marks': typeof AuthenticatedMadrassaExamsIdMarksRoute
  '/_authenticated/madrassa/exams/$id/results': typeof AuthenticatedMadrassaExamsIdResultsRoute
  '/_authenticated/school/exams/$id/results': typeof AuthenticatedSchoolExamsIdResultsRoute
  '/_authenticated/school/exams/$id/seating': typeof AuthenticatedSchoolExamsIdSeatingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/change-password'
    | '/login'
    | '/website'
    | '/audit'
    | '/dashboard'
    | '/finance'
    | '/holidays'
    | '/id-cards'
    | '/inventory'
    | '/notifications'
    | '/parents'
    | '/reports'
    | '/teachers'
    | '/users'
    | '/website/contact'
    | '/website/gallery'
    | '/website/'
    | '/admission/new'
    | '/admission/queue'
    | '/finance/donations'
    | '/madrassa/attendance'
    | '/madrassa/categories'
    | '/madrassa/classes'
    | '/madrassa/exams'
    | '/madrassa/fees'
    | '/madrassa/hifz'
    | '/madrassa/students'
    | '/madrassa/subjects'
    | '/madrassa/timetable'
    | '/reports/annual'
    | '/reports/attendance'
    | '/reports/category'
    | '/reports/monthly'
    | '/school/attendance'
    | '/school/classes'
    | '/school/exams'
    | '/school/fees'
    | '/school/students'
    | '/school/subjects'
    | '/school/timetable'
    | '/settings/academic-year'
    | '/settings/concessions'
    | '/settings/templates'
    | '/settings/website'
    | '/students/$id'
    | '/teachers/$id'
    | '/teachers/salary'
    | '/admission/'
    | '/settings/'
    | '/madrassa/exams/$id'
    | '/madrassa/exams/board'
    | '/school/exams/$id'
    | '/school/exams/board'
    | '/madrassa/exams/$id/marks'
    | '/madrassa/exams/$id/results'
    | '/school/exams/$id/results'
    | '/school/exams/$id/seating'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/change-password'
    | '/login'
    | '/audit'
    | '/dashboard'
    | '/finance'
    | '/holidays'
    | '/id-cards'
    | '/inventory'
    | '/notifications'
    | '/parents'
    | '/reports'
    | '/teachers'
    | '/users'
    | '/website/contact'
    | '/website/gallery'
    | '/website'
    | '/admission/new'
    | '/admission/queue'
    | '/finance/donations'
    | '/madrassa/attendance'
    | '/madrassa/categories'
    | '/madrassa/classes'
    | '/madrassa/exams'
    | '/madrassa/fees'
    | '/madrassa/hifz'
    | '/madrassa/students'
    | '/madrassa/subjects'
    | '/madrassa/timetable'
    | '/reports/annual'
    | '/reports/attendance'
    | '/reports/category'
    | '/reports/monthly'
    | '/school/attendance'
    | '/school/classes'
    | '/school/exams'
    | '/school/fees'
    | '/school/students'
    | '/school/subjects'
    | '/school/timetable'
    | '/settings/academic-year'
    | '/settings/concessions'
    | '/settings/templates'
    | '/settings/website'
    | '/students/$id'
    | '/teachers/$id'
    | '/teachers/salary'
    | '/admission'
    | '/settings'
    | '/madrassa/exams/$id'
    | '/madrassa/exams/board'
    | '/school/exams/$id'
    | '/school/exams/board'
    | '/madrassa/exams/$id/marks'
    | '/madrassa/exams/$id/results'
    | '/school/exams/$id/results'
    | '/school/exams/$id/seating'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/apply'
    | '/change-password'
    | '/login'
    | '/website'
    | '/_authenticated/audit'
    | '/_authenticated/dashboard'
    | '/_authenticated/finance'
    | '/_authenticated/holidays'
    | '/_authenticated/id-cards'
    | '/_authenticated/inventory'
    | '/_authenticated/notifications'
    | '/_authenticated/parents'
    | '/_authenticated/reports'
    | '/_authenticated/teachers'
    | '/_authenticated/users'
    | '/website/contact'
    | '/website/gallery'
    | '/website/'
    | '/_authenticated/admission/new'
    | '/_authenticated/admission/queue'
    | '/_authenticated/finance/donations'
    | '/_authenticated/madrassa/attendance'
    | '/_authenticated/madrassa/categories'
    | '/_authenticated/madrassa/classes'
    | '/_authenticated/madrassa/exams'
    | '/_authenticated/madrassa/fees'
    | '/_authenticated/madrassa/hifz'
    | '/_authenticated/madrassa/students'
    | '/_authenticated/madrassa/subjects'
    | '/_authenticated/madrassa/timetable'
    | '/_authenticated/reports/annual'
    | '/_authenticated/reports/attendance'
    | '/_authenticated/reports/category'
    | '/_authenticated/reports/monthly'
    | '/_authenticated/school/attendance'
    | '/_authenticated/school/classes'
    | '/_authenticated/school/exams'
    | '/_authenticated/school/fees'
    | '/_authenticated/school/students'
    | '/_authenticated/school/subjects'
    | '/_authenticated/school/timetable'
    | '/_authenticated/settings/academic-year'
    | '/_authenticated/settings/concessions'
    | '/_authenticated/settings/templates'
    | '/_authenticated/settings/website'
    | '/_authenticated/students/$id'
    | '/_authenticated/teachers/$id'
    | '/_authenticated/teachers/salary'
    | '/_authenticated/admission/'
    | '/_authenticated/settings/'
    | '/_authenticated/madrassa/exams/$id'
    | '/_authenticated/madrassa/exams/board'
    | '/_authenticated/school/exams/$id'
    | '/_authenticated/school/exams/board'
    | '/_authenticated/madrassa/exams/$id/marks'
    | '/_authenticated/madrassa/exams/$id/results'
    | '/_authenticated/school/exams/$id/results'
    | '/_authenticated/school/exams/$id/seating'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
  WebsiteRoute: typeof WebsiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/website': {
      id: '/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof WebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website/': {
      id: '/website/'
      path: '/'
      fullPath: '/website/'
      preLoaderRoute: typeof WebsiteIndexRouteImport
      parentRoute: typeof WebsiteRoute
    }
    '/website/gallery': {
      id: '/website/gallery'
      path: '/gallery'
      fullPath: '/website/gallery'
      preLoaderRoute: typeof WebsiteGalleryRouteImport
      parentRoute: typeof WebsiteRoute
    }
    '/website/contact': {
      id: '/website/contact'
      path: '/contact'
      fullPath: '/website/contact'
      preLoaderRoute: typeof WebsiteContactRouteImport
      parentRoute: typeof WebsiteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teachers': {
      id: '/_authenticated/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AuthenticatedTeachersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parents': {
      id: '/_authenticated/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof AuthenticatedParentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/id-cards': {
      id: '/_authenticated/id-cards'
      path: '/id-cards'
      fullPath: '/id-cards'
      preLoaderRoute: typeof AuthenticatedIdCardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/holidays': {
      id: '/_authenticated/holidays'
      path: '/holidays'
      fullPath: '/holidays'
      preLoaderRoute: typeof AuthenticatedHolidaysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admission/': {
      id: '/_authenticated/admission/'
      path: '/admission'
      fullPath: '/admission/'
      preLoaderRoute: typeof AuthenticatedAdmissionIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teachers/salary': {
      id: '/_authenticated/teachers/salary'
      path: '/salary'
      fullPath: '/teachers/salary'
      preLoaderRoute: typeof AuthenticatedTeachersSalaryRouteImport
      parentRoute: typeof AuthenticatedTeachersRoute
    }
    '/_authenticated/teachers/$id': {
      id: '/_authenticated/teachers/$id'
      path: '/$id'
      fullPath: '/teachers/$id'
      preLoaderRoute: typeof AuthenticatedTeachersIdRouteImport
      parentRoute: typeof AuthenticatedTeachersRoute
    }
    '/_authenticated/students/$id': {
      id: '/_authenticated/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AuthenticatedStudentsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/website': {
      id: '/_authenticated/settings/website'
      path: '/settings/website'
      fullPath: '/settings/website'
      preLoaderRoute: typeof AuthenticatedSettingsWebsiteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/templates': {
      id: '/_authenticated/settings/templates'
      path: '/settings/templates'
      fullPath: '/settings/templates'
      preLoaderRoute: typeof AuthenticatedSettingsTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/concessions': {
      id: '/_authenticated/settings/concessions'
      path: '/settings/concessions'
      fullPath: '/settings/concessions'
      preLoaderRoute: typeof AuthenticatedSettingsConcessionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/academic-year': {
      id: '/_authenticated/settings/academic-year'
      path: '/settings/academic-year'
      fullPath: '/settings/academic-year'
      preLoaderRoute: typeof AuthenticatedSettingsAcademicYearRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/school/timetable': {
      id: '/_authenticated/school/timetable'
      path: '/school/timetable'
      fullPath: '/school/timetable'
      preLoaderRoute: typeof AuthenticatedSchoolTimetableRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/school/subjects': {
      id: '/_authenticated/school/subjects'
      path: '/school/subjects'
      fullPath: '/school/subjects'
      preLoaderRoute: typeof AuthenticatedSchoolSubjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/school/students': {
      id: '/_authenticated/school/students'
      path: '/school/students'
      fullPath: '/school/students'
      preLoaderRoute: typeof AuthenticatedSchoolStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/school/fees': {
      id: '/_authenticated/school/fees'
      path: '/school/fees'
      fullPath: '/school/fees'
      preLoaderRoute: typeof AuthenticatedSchoolFeesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/school/exams': {
      id: '/_authenticated/school/exams'
      path: '/school/exams'
      fullPath: '/school/exams'
      preLoaderRoute: typeof AuthenticatedSchoolExamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/school/classes': {
      id: '/_authenticated/school/classes'
      path: '/school/classes'
      fullPath: '/school/classes'
      preLoaderRoute: typeof AuthenticatedSchoolClassesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/school/attendance': {
      id: '/_authenticated/school/attendance'
      path: '/school/attendance'
      fullPath: '/school/attendance'
      preLoaderRoute: typeof AuthenticatedSchoolAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/monthly': {
      id: '/_authenticated/reports/monthly'
      path: '/monthly'
      fullPath: '/reports/monthly'
      preLoaderRoute: typeof AuthenticatedReportsMonthlyRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/category': {
      id: '/_authenticated/reports/category'
      path: '/category'
      fullPath: '/reports/category'
      preLoaderRoute: typeof AuthenticatedReportsCategoryRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/attendance': {
      id: '/_authenticated/reports/attendance'
      path: '/attendance'
      fullPath: '/reports/attendance'
      preLoaderRoute: typeof AuthenticatedReportsAttendanceRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/annual': {
      id: '/_authenticated/reports/annual'
      path: '/annual'
      fullPath: '/reports/annual'
      preLoaderRoute: typeof AuthenticatedReportsAnnualRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/madrassa/timetable': {
      id: '/_authenticated/madrassa/timetable'
      path: '/madrassa/timetable'
      fullPath: '/madrassa/timetable'
      preLoaderRoute: typeof AuthenticatedMadrassaTimetableRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/madrassa/subjects': {
      id: '/_authenticated/madrassa/subjects'
      path: '/madrassa/subjects'
      fullPath: '/madrassa/subjects'
      preLoaderRoute: typeof AuthenticatedMadrassaSubjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/madrassa/students': {
      id: '/_authenticated/madrassa/students'
      path: '/madrassa/students'
      fullPath: '/madrassa/students'
      preLoaderRoute: typeof AuthenticatedMadrassaStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/madrassa/hifz': {
      id: '/_authenticated/madrassa/hifz'
      path: '/madrassa/hifz'
      fullPath: '/madrassa/hifz'
      preLoaderRoute: typeof AuthenticatedMadrassaHifzRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/madrassa/fees': {
      id: '/_authenticated/madrassa/fees'
      path: '/madrassa/fees'
      fullPath: '/madrassa/fees'
      preLoaderRoute: typeof AuthenticatedMadrassaFeesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/madrassa/exams': {
      id: '/_authenticated/madrassa/exams'
      path: '/madrassa/exams'
      fullPath: '/madrassa/exams'
      preLoaderRoute: typeof AuthenticatedMadrassaExamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/madrassa/classes': {
      id: '/_authenticated/madrassa/classes'
      path: '/madrassa/classes'
      fullPath: '/madrassa/classes'
      preLoaderRoute: typeof AuthenticatedMadrassaClassesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/madrassa/categories': {
      id: '/_authenticated/madrassa/categories'
      path: '/madrassa/categories'
      fullPath: '/madrassa/categories'
      preLoaderRoute: typeof AuthenticatedMadrassaCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/madrassa/attendance': {
      id: '/_authenticated/madrassa/attendance'
      path: '/madrassa/attendance'
      fullPath: '/madrassa/attendance'
      preLoaderRoute: typeof AuthenticatedMadrassaAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance/donations': {
      id: '/_authenticated/finance/donations'
      path: '/donations'
      fullPath: '/finance/donations'
      preLoaderRoute: typeof AuthenticatedFinanceDonationsRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/admission/queue': {
      id: '/_authenticated/admission/queue'
      path: '/admission/queue'
      fullPath: '/admission/queue'
      preLoaderRoute: typeof AuthenticatedAdmissionQueueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admission/new': {
      id: '/_authenticated/admission/new'
      path: '/admission/new'
      fullPath: '/admission/new'
      preLoaderRoute: typeof AuthenticatedAdmissionNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/school/exams/board': {
      id: '/_authenticated/school/exams/board'
      path: '/board'
      fullPath: '/school/exams/board'
      preLoaderRoute: typeof AuthenticatedSchoolExamsBoardRouteImport
      parentRoute: typeof AuthenticatedSchoolExamsRoute
    }
    '/_authenticated/school/exams/$id': {
      id: '/_authenticated/school/exams/$id'
      path: '/$id'
      fullPath: '/school/exams/$id'
      preLoaderRoute: typeof AuthenticatedSchoolExamsIdRouteImport
      parentRoute: typeof AuthenticatedSchoolExamsRoute
    }
    '/_authenticated/madrassa/exams/board': {
      id: '/_authenticated/madrassa/exams/board'
      path: '/board'
      fullPath: '/madrassa/exams/board'
      preLoaderRoute: typeof AuthenticatedMadrassaExamsBoardRouteImport
      parentRoute: typeof AuthenticatedMadrassaExamsRoute
    }
    '/_authenticated/madrassa/exams/$id': {
      id: '/_authenticated/madrassa/exams/$id'
      path: '/$id'
      fullPath: '/madrassa/exams/$id'
      preLoaderRoute: typeof AuthenticatedMadrassaExamsIdRouteImport
      parentRoute: typeof AuthenticatedMadrassaExamsRoute
    }
    '/_authenticated/school/exams/$id/seating': {
      id: '/_authenticated/school/exams/$id/seating'
      path: '/seating'
      fullPath: '/school/exams/$id/seating'
      preLoaderRoute: typeof AuthenticatedSchoolExamsIdSeatingRouteImport
      parentRoute: typeof AuthenticatedSchoolExamsIdRoute
    }
    '/_authenticated/school/exams/$id/results': {
      id: '/_authenticated/school/exams/$id/results'
      path: '/results'
      fullPath: '/school/exams/$id/results'
      preLoaderRoute: typeof AuthenticatedSchoolExamsIdResultsRouteImport
      parentRoute: typeof AuthenticatedSchoolExamsIdRoute
    }
    '/_authenticated/madrassa/exams/$id/results': {
      id: '/_authenticated/madrassa/exams/$id/results'
      path: '/results'
      fullPath: '/madrassa/exams/$id/results'
      preLoaderRoute: typeof AuthenticatedMadrassaExamsIdResultsRouteImport
      parentRoute: typeof AuthenticatedMadrassaExamsIdRoute
    }
    '/_authenticated/madrassa/exams/$id/marks': {
      id: '/_authenticated/madrassa/exams/$id/marks'
      path: '/marks'
      fullPath: '/madrassa/exams/$id/marks'
      preLoaderRoute: typeof AuthenticatedMadrassaExamsIdMarksRouteImport
      parentRoute: typeof AuthenticatedMadrassaExamsIdRoute
    }
  }
}

interface AuthenticatedFinanceRouteChildren {
  AuthenticatedFinanceDonationsRoute: typeof AuthenticatedFinanceDonationsRoute
}

const AuthenticatedFinanceRouteChildren: AuthenticatedFinanceRouteChildren = {
  AuthenticatedFinanceDonationsRoute: AuthenticatedFinanceDonationsRoute,
}

const AuthenticatedFinanceRouteWithChildren =
  AuthenticatedFinanceRoute._addFileChildren(AuthenticatedFinanceRouteChildren)

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsAnnualRoute: typeof AuthenticatedReportsAnnualRoute
  AuthenticatedReportsAttendanceRoute: typeof AuthenticatedReportsAttendanceRoute
  AuthenticatedReportsCategoryRoute: typeof AuthenticatedReportsCategoryRoute
  AuthenticatedReportsMonthlyRoute: typeof AuthenticatedReportsMonthlyRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsAnnualRoute: AuthenticatedReportsAnnualRoute,
  AuthenticatedReportsAttendanceRoute: AuthenticatedReportsAttendanceRoute,
  AuthenticatedReportsCategoryRoute: AuthenticatedReportsCategoryRoute,
  AuthenticatedReportsMonthlyRoute: AuthenticatedReportsMonthlyRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedTeachersRouteChildren {
  AuthenticatedTeachersIdRoute: typeof AuthenticatedTeachersIdRoute
  AuthenticatedTeachersSalaryRoute: typeof AuthenticatedTeachersSalaryRoute
}

const AuthenticatedTeachersRouteChildren: AuthenticatedTeachersRouteChildren = {
  AuthenticatedTeachersIdRoute: AuthenticatedTeachersIdRoute,
  AuthenticatedTeachersSalaryRoute: AuthenticatedTeachersSalaryRoute,
}

const AuthenticatedTeachersRouteWithChildren =
  AuthenticatedTeachersRoute._addFileChildren(
    AuthenticatedTeachersRouteChildren,
  )

interface AuthenticatedMadrassaExamsIdRouteChildren {
  AuthenticatedMadrassaExamsIdMarksRoute: typeof AuthenticatedMadrassaExamsIdMarksRoute
  AuthenticatedMadrassaExamsIdResultsRoute: typeof AuthenticatedMadrassaExamsIdResultsRoute
}

const AuthenticatedMadrassaExamsIdRouteChildren: AuthenticatedMadrassaExamsIdRouteChildren =
  {
    AuthenticatedMadrassaExamsIdMarksRoute:
      AuthenticatedMadrassaExamsIdMarksRoute,
    AuthenticatedMadrassaExamsIdResultsRoute:
      AuthenticatedMadrassaExamsIdResultsRoute,
  }

const AuthenticatedMadrassaExamsIdRouteWithChildren =
  AuthenticatedMadrassaExamsIdRoute._addFileChildren(
    AuthenticatedMadrassaExamsIdRouteChildren,
  )

interface AuthenticatedMadrassaExamsRouteChildren {
  AuthenticatedMadrassaExamsIdRoute: typeof AuthenticatedMadrassaExamsIdRouteWithChildren
  AuthenticatedMadrassaExamsBoardRoute: typeof AuthenticatedMadrassaExamsBoardRoute
}

const AuthenticatedMadrassaExamsRouteChildren: AuthenticatedMadrassaExamsRouteChildren =
  {
    AuthenticatedMadrassaExamsIdRoute:
      AuthenticatedMadrassaExamsIdRouteWithChildren,
    AuthenticatedMadrassaExamsBoardRoute: AuthenticatedMadrassaExamsBoardRoute,
  }

const AuthenticatedMadrassaExamsRouteWithChildren =
  AuthenticatedMadrassaExamsRoute._addFileChildren(
    AuthenticatedMadrassaExamsRouteChildren,
  )

interface AuthenticatedSchoolExamsIdRouteChildren {
  AuthenticatedSchoolExamsIdResultsRoute: typeof AuthenticatedSchoolExamsIdResultsRoute
  AuthenticatedSchoolExamsIdSeatingRoute: typeof AuthenticatedSchoolExamsIdSeatingRoute
}

const AuthenticatedSchoolExamsIdRouteChildren: AuthenticatedSchoolExamsIdRouteChildren =
  {
    AuthenticatedSchoolExamsIdResultsRoute:
      AuthenticatedSchoolExamsIdResultsRoute,
    AuthenticatedSchoolExamsIdSeatingRoute:
      AuthenticatedSchoolExamsIdSeatingRoute,
  }

const AuthenticatedSchoolExamsIdRouteWithChildren =
  AuthenticatedSchoolExamsIdRoute._addFileChildren(
    AuthenticatedSchoolExamsIdRouteChildren,
  )

interface AuthenticatedSchoolExamsRouteChildren {
  AuthenticatedSchoolExamsIdRoute: typeof AuthenticatedSchoolExamsIdRouteWithChildren
  AuthenticatedSchoolExamsBoardRoute: typeof AuthenticatedSchoolExamsBoardRoute
}

const AuthenticatedSchoolExamsRouteChildren: AuthenticatedSchoolExamsRouteChildren =
  {
    AuthenticatedSchoolExamsIdRoute:
      AuthenticatedSchoolExamsIdRouteWithChildren,
    AuthenticatedSchoolExamsBoardRoute: AuthenticatedSchoolExamsBoardRoute,
  }

const AuthenticatedSchoolExamsRouteWithChildren =
  AuthenticatedSchoolExamsRoute._addFileChildren(
    AuthenticatedSchoolExamsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRouteWithChildren
  AuthenticatedHolidaysRoute: typeof AuthenticatedHolidaysRoute
  AuthenticatedIdCardsRoute: typeof AuthenticatedIdCardsRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedParentsRoute: typeof AuthenticatedParentsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedTeachersRoute: typeof AuthenticatedTeachersRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedAdmissionNewRoute: typeof AuthenticatedAdmissionNewRoute
  AuthenticatedAdmissionQueueRoute: typeof AuthenticatedAdmissionQueueRoute
  AuthenticatedMadrassaAttendanceRoute: typeof AuthenticatedMadrassaAttendanceRoute
  AuthenticatedMadrassaCategoriesRoute: typeof AuthenticatedMadrassaCategoriesRoute
  AuthenticatedMadrassaClassesRoute: typeof AuthenticatedMadrassaClassesRoute
  AuthenticatedMadrassaExamsRoute: typeof AuthenticatedMadrassaExamsRouteWithChildren
  AuthenticatedMadrassaFeesRoute: typeof AuthenticatedMadrassaFeesRoute
  AuthenticatedMadrassaHifzRoute: typeof AuthenticatedMadrassaHifzRoute
  AuthenticatedMadrassaStudentsRoute: typeof AuthenticatedMadrassaStudentsRoute
  AuthenticatedMadrassaSubjectsRoute: typeof AuthenticatedMadrassaSubjectsRoute
  AuthenticatedMadrassaTimetableRoute: typeof AuthenticatedMadrassaTimetableRoute
  AuthenticatedSchoolAttendanceRoute: typeof AuthenticatedSchoolAttendanceRoute
  AuthenticatedSchoolClassesRoute: typeof AuthenticatedSchoolClassesRoute
  AuthenticatedSchoolExamsRoute: typeof AuthenticatedSchoolExamsRouteWithChildren
  AuthenticatedSchoolFeesRoute: typeof AuthenticatedSchoolFeesRoute
  AuthenticatedSchoolStudentsRoute: typeof AuthenticatedSchoolStudentsRoute
  AuthenticatedSchoolSubjectsRoute: typeof AuthenticatedSchoolSubjectsRoute
  AuthenticatedSchoolTimetableRoute: typeof AuthenticatedSchoolTimetableRoute
  AuthenticatedSettingsAcademicYearRoute: typeof AuthenticatedSettingsAcademicYearRoute
  AuthenticatedSettingsConcessionsRoute: typeof AuthenticatedSettingsConcessionsRoute
  AuthenticatedSettingsTemplatesRoute: typeof AuthenticatedSettingsTemplatesRoute
  AuthenticatedSettingsWebsiteRoute: typeof AuthenticatedSettingsWebsiteRoute
  AuthenticatedStudentsIdRoute: typeof AuthenticatedStudentsIdRoute
  AuthenticatedAdmissionIndexRoute: typeof AuthenticatedAdmissionIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRouteWithChildren,
  AuthenticatedHolidaysRoute: AuthenticatedHolidaysRoute,
  AuthenticatedIdCardsRoute: AuthenticatedIdCardsRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedParentsRoute: AuthenticatedParentsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedTeachersRoute: AuthenticatedTeachersRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedAdmissionNewRoute: AuthenticatedAdmissionNewRoute,
  AuthenticatedAdmissionQueueRoute: AuthenticatedAdmissionQueueRoute,
  AuthenticatedMadrassaAttendanceRoute: AuthenticatedMadrassaAttendanceRoute,
  AuthenticatedMadrassaCategoriesRoute: AuthenticatedMadrassaCategoriesRoute,
  AuthenticatedMadrassaClassesRoute: AuthenticatedMadrassaClassesRoute,
  AuthenticatedMadrassaExamsRoute: AuthenticatedMadrassaExamsRouteWithChildren,
  AuthenticatedMadrassaFeesRoute: AuthenticatedMadrassaFeesRoute,
  AuthenticatedMadrassaHifzRoute: AuthenticatedMadrassaHifzRoute,
  AuthenticatedMadrassaStudentsRoute: AuthenticatedMadrassaStudentsRoute,
  AuthenticatedMadrassaSubjectsRoute: AuthenticatedMadrassaSubjectsRoute,
  AuthenticatedMadrassaTimetableRoute: AuthenticatedMadrassaTimetableRoute,
  AuthenticatedSchoolAttendanceRoute: AuthenticatedSchoolAttendanceRoute,
  AuthenticatedSchoolClassesRoute: AuthenticatedSchoolClassesRoute,
  AuthenticatedSchoolExamsRoute: AuthenticatedSchoolExamsRouteWithChildren,
  AuthenticatedSchoolFeesRoute: AuthenticatedSchoolFeesRoute,
  AuthenticatedSchoolStudentsRoute: AuthenticatedSchoolStudentsRoute,
  AuthenticatedSchoolSubjectsRoute: AuthenticatedSchoolSubjectsRoute,
  AuthenticatedSchoolTimetableRoute: AuthenticatedSchoolTimetableRoute,
  AuthenticatedSettingsAcademicYearRoute:
    AuthenticatedSettingsAcademicYearRoute,
  AuthenticatedSettingsConcessionsRoute: AuthenticatedSettingsConcessionsRoute,
  AuthenticatedSettingsTemplatesRoute: AuthenticatedSettingsTemplatesRoute,
  AuthenticatedSettingsWebsiteRoute: AuthenticatedSettingsWebsiteRoute,
  AuthenticatedStudentsIdRoute: AuthenticatedStudentsIdRoute,
  AuthenticatedAdmissionIndexRoute: AuthenticatedAdmissionIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface WebsiteRouteChildren {
  WebsiteContactRoute: typeof WebsiteContactRoute
  WebsiteGalleryRoute: typeof WebsiteGalleryRoute
  WebsiteIndexRoute: typeof WebsiteIndexRoute
}

const WebsiteRouteChildren: WebsiteRouteChildren = {
  WebsiteContactRoute: WebsiteContactRoute,
  WebsiteGalleryRoute: WebsiteGalleryRoute,
  WebsiteIndexRoute: WebsiteIndexRoute,
}

const WebsiteRouteWithChildren =
  WebsiteRoute._addFileChildren(WebsiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ApplyRoute: ApplyRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
  WebsiteRoute: WebsiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
